-- ============================================
-- CREACI脫N DE TABLAS BASE
-- ============================================

CREATE TABLE IF NOT EXISTS "AIs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AIs" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ParentId" integer,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "DeliverableTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "Description" character varying(500),
    "IsRequired" boolean NOT NULL DEFAULT FALSE,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "SortOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_DeliverableTypes" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "Platforms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "ImageUrl" text NOT NULL,
    "PlatformWebsiteUrl" text NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Platforms" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "ProcessedWebhookEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" character varying(255) NOT NULL,
    "EventType" character varying(100) NOT NULL,
    "StripeAccountId" character varying(255),
    "UserId" integer,
    "ProcessedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "Status" character varying(50) NOT NULL DEFAULT 'Success',
    "ErrorMessage" text,
    "EventData" text,
    CONSTRAINT "PK_ProcessedWebhookEvents" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "ServiceTypeCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Position" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_ServiceTypeCategories" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "Severities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(20) NOT NULL,
    "Description" character varying(100),
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Severities" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "SubscriptionPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "imageUrl" text NOT NULL,
    "PriceMonthly" numeric NOT NULL,
    "PriceYearly" numeric NOT NULL,
    "HumanFilter" boolean NOT NULL,
    "AdvanceIAModels" boolean NOT NULL,
    "AdvancedAdImagesAnalysis" boolean NOT NULL,
    "MaxSearches" integer NOT NULL,
    "MinSearchInterval" integer NOT NULL,
    "StripePriceIdMonthly" text,
    "StripePriceIdYearly" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "SystemStatuses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StatusType" character varying(50) NOT NULL,
    "StatusName" character varying(50) NOT NULL,
    "StatusValue" character varying(50) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Color" character varying(20),
    "IsActive" boolean NOT NULL,
    "IsFinalizationStatus" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SystemStatuses" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "SystemSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IsWhatsAppNotificationEnabled" boolean NOT NULL,
    "IsEmailNotificationEnabled" boolean NOT NULL,
    "Theme" text NOT NULL,
    "AIId" integer,
    "StripeMode" character varying(20) NOT NULL,
    "StripeModeChangedAt" timestamp with time zone,
    "StripeModeChangedByUserId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SystemSettings_AIs_AIId" FOREIGN KEY ("AIId") REFERENCES "AIs" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "Ads" (
    "Id" text NOT NULL,
    "Description" text NOT NULL,
    "Title" text NOT NULL,
    "Url" text NOT NULL,
    "Price" numeric,
    "Images" text[] NOT NULL,
    "AdScore" integer,
    "FinalScore" integer,
    "GoodThings" text[] NOT NULL,
    "BadThings" text[] NOT NULL,
    "PublishDate" timestamp with time zone,
    "Category" text NOT NULL,
    "CategoryId" integer,
    "Province" text NOT NULL,
    "ProvinceId" integer,
    "City" text NOT NULL,
    "CityId" integer,
    "Highlighted" boolean NOT NULL,
    "IsNew" boolean NOT NULL,
    "IsReserved" boolean NOT NULL,
    "Slug" text NOT NULL,
    "SellerType" text NOT NULL,
    "Tags" text[] NOT NULL,
    "PlatformId" integer NOT NULL,
    "UpdateDate" timestamp with time zone,
    "ScrappedDate" timestamp with time zone,
    CONSTRAINT "PK_Ads" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Ads_Platforms_PlatformId" FOREIGN KEY ("PlatformId") REFERENCES "Platforms" ("Id") ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "PlatformCategoryMappings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlatformId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "UrlParameter" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlatformCategoryMappings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlatformCategoryMappings_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PlatformCategoryMappings_Platforms_PlatformId" FOREIGN KEY ("PlatformId") REFERENCES "Platforms" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "ServiceTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "ServiceTypeCategoryId" integer,
    "Position" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "RequiresAppointment" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_ServiceTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServiceTypes_ServiceTypeCategories_ServiceTypeCategoryId" FOREIGN KEY ("ServiceTypeCategoryId") REFERENCES "ServiceTypeCategories" ("Id") ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "LogTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(200),
    "SeverityId" integer,
    "RequiresAdminNotification" boolean NOT NULL,
    "RequiresEmailAlert" boolean NOT NULL,
    "RequiresSmsAlert" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_LogTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LogTypes_Severities_SeverityId" FOREIGN KEY ("SeverityId") REFERENCES "Severities" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text,
    "GoogleId" text NOT NULL,
    "PhoneNumber" text,
    "PhoneVerified" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsBlocked" boolean NOT NULL,
    "Role" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "SubscriptionPlanId" integer,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_SubscriptionPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "StatusConfigurations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StatusId" integer NOT NULL,
    "CategoryId" integer,
    "ServiceTypeCategoryId" integer,
    "ClientPercentage" numeric NOT NULL,
    "ExpertPercentage" numeric NOT NULL,
    "PlatformPercentage" numeric NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StatusConfigurations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StatusConfigurations_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_StatusConfigurations_ServiceTypeCategories_ServiceTypeCateg~" FOREIGN KEY ("ServiceTypeCategoryId") REFERENCES "ServiceTypeCategories" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_StatusConfigurations_SystemStatuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "StatusMappings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SourceStatusId" integer NOT NULL,
    "TargetStatusId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StatusMappings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StatusMappings_SystemStatuses_SourceStatusId" FOREIGN KEY ("SourceStatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StatusMappings_SystemStatuses_TargetStatusId" FOREIGN KEY ("TargetStatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "ExpertProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ProfilePictureUrl" text NOT NULL,
    "ProfilePictureObjectName" text NOT NULL,
    "Description" text NOT NULL,
    "StripeAccountId" text,
    "PendingStripeAccountId" text,
    "OnboardingCompleted" boolean NOT NULL,
    "StripeStatus" integer NOT NULL,
    "StripeStatusDetails" text,
    "StripeFutureRequirements" text,
    "StripeFutureDueAt" timestamp with time zone,
    "IsOnVacation" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Latitude" text NOT NULL,
    "Longitude" text NOT NULL,
    "Timezone" text NOT NULL,
    "Country" text,
    CONSTRAINT "PK_ExpertProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExpertProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "FinancialTransactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "Amount" numeric NOT NULL,
    "TransactionType" text NOT NULL,
    "RelatedEntityType" text,
    "RelatedEntityId" integer,
    "StripeTransferId" text,
    "StripePaymentIntentId" text,
    "StripeRefundId" text,
    "IsRefunded" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FinancialTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FinancialTransactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "Likes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "AdId" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Likes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Likes_Ads_AdId" FOREIGN KEY ("AdId") REFERENCES "Ads" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Likes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Logs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Message" text NOT NULL,
    "Details" text,
    "UserId" integer,
    "Source" text,
    "LogTypeId" integer,
    "RelatedEntityType" text,
    "RelatedEntityId" integer,
    "AdditionalData" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Logs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Logs_LogTypes_LogTypeId" FOREIGN KEY ("LogTypeId") REFERENCES "LogTypes" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Logs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "Notifications" (
    "Id" uuid NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Type" text NOT NULL,
    "Url" text,
    "ImageUrl" text,
    "UserId" integer,
    "Read" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Token" character varying(500) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "RevokedAt" timestamp with time zone,
    "RevokedByIp" character varying(100),
    "CreatedByIp" character varying(100) NOT NULL,
    "ReplacedByToken" character varying(200),
    "DeviceInfo" character varying(500),
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Searches" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Frequency" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "LastExecution" timestamp with time zone NOT NULL,
    "NextExecution" timestamp with time zone NOT NULL,
    "IsRevised" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "SubscriptionPlanId" integer,
    CONSTRAINT "PK_Searches" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Searches_SubscriptionPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id"),
    CONSTRAINT "FK_Searches_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "UserMfaSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "TotpSecret" character varying(500) NOT NULL,
    "RecoveryCodesEncrypted" character varying(2000),
    "RecoveryCodesUsed" integer NOT NULL,
    "EnabledAt" timestamp with time zone,
    "LastVerifiedAt" timestamp with time zone,
    "FailedAttempts" integer NOT NULL,
    "LockedUntil" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_UserMfaSettings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserMfaSettings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "UserSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "IsWhatsAppEnabled" boolean NOT NULL,
    "IsEmailEnabled" boolean NOT NULL,
    "Theme" text NOT NULL,
    "AIId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserSettings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserSettings_AIs_AIId" FOREIGN KEY ("AIId") REFERENCES "AIs" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_UserSettings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "UserSubscriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "SubscriptionPlanId" integer NOT NULL,
    "IsYearly" boolean NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "StripeSubscriptionId" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserSubscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserSubscriptions_SubscriptionPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserSubscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "ExpertAvailabilities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ExpertId" integer NOT NULL,
    "DaysOfWeek" text NOT NULL,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    "EffectiveFrom" timestamp with time zone NOT NULL,
    "EffectiveTo" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExpertAvailabilities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExpertAvailabilities_ExpertProfiles_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "ExpertProfiles" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "SearchServices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ExpertProfileId" integer,
    "AIId" integer,
    "CategoryId" integer NOT NULL,
    "ServiceTypeId" integer NOT NULL,
    "Price" numeric NOT NULL,
    "Conditions" text NOT NULL,
    "DurationInHours" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_SearchServices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SearchServices_AIs_AIId" FOREIGN KEY ("AIId") REFERENCES "AIs" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_SearchServices_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SearchServices_ExpertProfiles_ExpertProfileId" FOREIGN KEY ("ExpertProfileId") REFERENCES "ExpertProfiles" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_SearchServices_ServiceTypes_ServiceTypeId" FOREIGN KEY ("ServiceTypeId") REFERENCES "ServiceTypes" ("Id") ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "SearchParameters" (
    "SearchParameterId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Keywords" text NOT NULL,
    "UserSearch" text NOT NULL,
    "Latitude" text NOT NULL,
    "Longitude" text NOT NULL,
    "LocationName" text,
    "ShippingAvailable" boolean NOT NULL,
    "StrictMatchOnly" boolean NOT NULL,
    "Category" integer,
    "LocationRange" integer,
    "MinPrice" integer,
    "MaxPrice" integer,
    "BrandId" integer,
    "ModelId" integer,
    "ServiceTypeId" integer,
    "SearchId" integer NOT NULL,
    CONSTRAINT "PK_SearchParameters" PRIMARY KEY ("SearchParameterId"),
    CONSTRAINT "FK_SearchParameters_Searches_SearchId" FOREIGN KEY ("SearchId") REFERENCES "Searches" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SearchParameters_ServiceTypes_ServiceTypeId" FOREIGN KEY ("ServiceTypeId") REFERENCES "ServiceTypes" ("Id") ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "SearchResults" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SearchId" integer NOT NULL,
    "AdId" text NOT NULL,
    "FoundAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SearchResults" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SearchResults_Ads_AdId" FOREIGN KEY ("AdId") REFERENCES "Ads" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SearchResults_Searches_SearchId" FOREIGN KEY ("SearchId") REFERENCES "Searches" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "SearchResultsFiltered" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SearchId" integer NOT NULL,
    "AdId" text NOT NULL,
    "FilteredAt" timestamp with time zone NOT NULL,
    "IsVisible" boolean NOT NULL,
    "FilterNotes" text,
    CONSTRAINT "PK_SearchResultsFiltered" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SearchResultsFiltered_Ads_AdId" FOREIGN KEY ("AdId") REFERENCES "Ads" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SearchResultsFiltered_Searches_SearchId" FOREIGN KEY ("SearchId") REFERENCES "Searches" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "SearchHires" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" integer,
    "ExpertId" integer,
    "SearchServiceId" integer NOT NULL,
    "SearchId" integer,
    "StatusId" integer NOT NULL,
    "ExpertTransferId" text,
    "Amount" numeric NOT NULL,
    "BaseAmount" numeric,
    "TaxAmount" numeric,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CompletionDeadline" timestamp with time zone,
    "ClientApproved" boolean,
    "ExpertAvailabilityId" integer,
    "ExpertTimezone" text,
    "ExpertCountry" text,
    CONSTRAINT "PK_SearchHires" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SearchHires_ExpertAvailabilities_ExpertAvailabilityId" FOREIGN KEY ("ExpertAvailabilityId") REFERENCES "ExpertAvailabilities" ("Id"),
    CONSTRAINT "FK_SearchHires_SearchServices_SearchServiceId" FOREIGN KEY ("SearchServiceId") REFERENCES "SearchServices" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SearchHires_Searches_SearchId" FOREIGN KEY ("SearchId") REFERENCES "Searches" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_SearchHires_SystemStatuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SearchHires_Users_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_SearchHires_Users_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "SearchServiceDeliverableTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SearchServiceId" integer NOT NULL,
    "DeliverableTypeId" integer NOT NULL,
    "IsSelected" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_SearchServiceDeliverableTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SearchServiceDeliverableTypes_DeliverableTypes_DeliverableT~" FOREIGN KEY ("DeliverableTypeId") REFERENCES "DeliverableTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SearchServiceDeliverableTypes_SearchServices_SearchServiceId" FOREIGN KEY ("SearchServiceId") REFERENCES "SearchServices" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "SearchServiceImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SearchServiceId" integer NOT NULL,
    "ImageUrl" text NOT NULL,
    "ImageObjectName" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SearchServiceImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SearchServiceImages_SearchServices_SearchServiceId" FOREIGN KEY ("SearchServiceId") REFERENCES "SearchServices" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "SearchParameterPlatforms" (
    "SearchParameterId" integer NOT NULL,
    "PlatformId" integer NOT NULL,
    CONSTRAINT "PK_SearchParameterPlatforms" PRIMARY KEY ("SearchParameterId", "PlatformId"),
    CONSTRAINT "FK_SearchParameterPlatforms_Platforms_PlatformId" FOREIGN KEY ("PlatformId") REFERENCES "Platforms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SearchParameterPlatforms_SearchParameters_SearchParameterId" FOREIGN KEY ("SearchParameterId") REFERENCES "SearchParameters" ("SearchParameterId") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Appointments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SearchHireId" integer NOT NULL,
    "StatusId" integer NOT NULL,
    "ProposedDate" timestamp with time zone NOT NULL,
    "ProposedTime" interval NOT NULL,
    "Location" character varying(500) NOT NULL,
    "Latitude" numeric,
    "Longitude" numeric,
    "DoorNumber" text,
    "OwnerPhone" text,
    "SiteDetails" text,
    "RejectionCount" integer NOT NULL DEFAULT 0,
    "ClientCancellationCount" integer NOT NULL DEFAULT 0,
    "ExpertCancellationCount" integer NOT NULL DEFAULT 0,
    "LastRejectionAt" timestamp with time zone,
    "LastClientCancellationAt" timestamp with time zone,
    "LastExpertCancellationAt" timestamp with time zone,
    "LastProposalAt" timestamp with time zone,
    "LastResponseAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Appointments_SystemStatuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "Conversations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SearchHireId" integer NOT NULL,
    "ClientId" integer,
    "ExpertId" integer,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Conversations_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Conversations_Users_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Conversations_Users_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "Disputes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SearchHireId" integer NOT NULL,
    "ReporterId" integer NOT NULL,
    "Reason" text NOT NULL,
    "Status" text NOT NULL,
    "ResolutionComments" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpertResponse" text,
    "ExpertResponseDeadline" timestamp with time zone,
    "ExpertResponseAt" timestamp with time zone,
    CONSTRAINT "PK_Disputes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Disputes_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Disputes_Users_ReporterId" FOREIGN KEY ("ReporterId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "Reviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReviewerId" integer,
    "ExpertId" integer,
    "SearchHireId" integer,
    "Score" integer NOT NULL,
    "Description" text NOT NULL,
    "Images" text[] NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Reviews_Users_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Reviews_Users_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "SearchHireDeliverables" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SearchHireId" integer NOT NULL,
    "Url" character varying(500) NOT NULL,
    "ObjectName" character varying(200) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SearchHireDeliverables" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SearchHireDeliverables_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "AppointmentTimers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AppointmentId" integer NOT NULL,
    "TimerType" character varying(50) NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "IsExpired" boolean NOT NULL DEFAULT FALSE,
    "ExpiredAt" timestamp with time zone,
    "Notes" text,
    "HangfireJobId" character varying(255),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_AppointmentTimers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AppointmentTimers_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ConversationId" integer NOT NULL,
    "SenderId" integer,
    "Content" character varying(5000),
    "SentAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "IsRead" boolean NOT NULL DEFAULT FALSE,
    "LocationLatitude" character varying(50),
    "LocationLongitude" character varying(50),
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Messages_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "DisputeFiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DisputeId" integer NOT NULL,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "FileType" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UploadedByUserId" integer NOT NULL,
    "FileCategory" text NOT NULL,
    CONSTRAINT "PK_DisputeFiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DisputeFiles_Disputes_DisputeId" FOREIGN KEY ("DisputeId") REFERENCES "Disputes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DisputeFiles_Users_UploadedByUserId" FOREIGN KEY ("UploadedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "ReviewImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReviewId" integer NOT NULL,
    "ImageUrl" text NOT NULL,
    "ImageObjectName" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ReviewImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReviewImages_Reviews_ReviewId" FOREIGN KEY ("ReviewId") REFERENCES "Reviews" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "MessageAttachments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" integer NOT NULL,
    "Url" character varying(500) NOT NULL,
    "ObjectName" character varying(200) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MessageAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MessageAttachments_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Ads_PlatformId" ON "Ads" ("PlatformId");


CREATE UNIQUE INDEX "IX_AIs_Name" ON "AIs" ("Name");


CREATE INDEX "IX_Appointments_ProposedDate" ON "Appointments" ("ProposedDate");


CREATE UNIQUE INDEX "IX_Appointments_SearchHireId" ON "Appointments" ("SearchHireId");


CREATE INDEX "IX_Appointments_StatusId" ON "Appointments" ("StatusId");


CREATE INDEX "IX_AppointmentTimers_AppointmentId" ON "AppointmentTimers" ("AppointmentId");


CREATE INDEX "IX_AppointmentTimers_EndTime" ON "AppointmentTimers" ("EndTime");


CREATE INDEX "IX_AppointmentTimers_IsExpired" ON "AppointmentTimers" ("IsExpired");


CREATE INDEX "IX_AppointmentTimers_TimerType" ON "AppointmentTimers" ("TimerType");


CREATE INDEX "IX_Categories_ParentId" ON "Categories" ("ParentId");


CREATE INDEX "IX_Conversations_ClientId" ON "Conversations" ("ClientId");


CREATE INDEX "IX_Conversations_ExpertId" ON "Conversations" ("ExpertId");


CREATE INDEX "IX_Conversations_SearchHireId" ON "Conversations" ("SearchHireId");


CREATE UNIQUE INDEX "IX_DeliverableTypes_Name" ON "DeliverableTypes" ("Name");


CREATE INDEX "IX_DisputeFiles_DisputeId" ON "DisputeFiles" ("DisputeId");


CREATE INDEX "IX_DisputeFiles_UploadedByUserId" ON "DisputeFiles" ("UploadedByUserId");


CREATE INDEX "IX_Disputes_ReporterId" ON "Disputes" ("ReporterId");


CREATE INDEX "IX_Disputes_SearchHireId" ON "Disputes" ("SearchHireId");


CREATE INDEX "IX_ExpertAvailabilities_ExpertId" ON "ExpertAvailabilities" ("ExpertId");


CREATE UNIQUE INDEX "IX_ExpertProfiles_UserId" ON "ExpertProfiles" ("UserId");


CREATE INDEX "IX_FinancialTransactions_UserId" ON "FinancialTransactions" ("UserId");


CREATE INDEX "IX_Likes_AdId" ON "Likes" ("AdId");


CREATE INDEX "IX_Likes_UserId" ON "Likes" ("UserId");


CREATE INDEX "IX_Logs_CreatedAt" ON "Logs" ("CreatedAt");


CREATE INDEX "IX_Logs_LogTypeId" ON "Logs" ("LogTypeId");


CREATE INDEX "IX_Logs_UserId" ON "Logs" ("UserId");


CREATE INDEX "IX_LogTypes_SeverityId" ON "LogTypes" ("SeverityId");


CREATE INDEX "IX_MessageAttachments_MessageId" ON "MessageAttachments" ("MessageId");


CREATE INDEX "IX_Messages_ConversationId" ON "Messages" ("ConversationId");


CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");


CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");


CREATE INDEX "IX_PlatformCategoryMappings_CategoryId" ON "PlatformCategoryMappings" ("CategoryId");


CREATE INDEX "IX_PlatformCategoryMappings_PlatformId" ON "PlatformCategoryMappings" ("PlatformId");


CREATE UNIQUE INDEX "IX_ProcessedWebhookEvents_EventId" ON "ProcessedWebhookEvents" ("EventId");


CREATE INDEX "IX_ProcessedWebhookEvents_StripeAccountId" ON "ProcessedWebhookEvents" ("StripeAccountId");


CREATE INDEX "IX_ProcessedWebhookEvents_UserId" ON "ProcessedWebhookEvents" ("UserId");


CREATE INDEX "IX_RefreshTokens_ExpiresAt" ON "RefreshTokens" ("ExpiresAt");


CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");


CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");


CREATE INDEX "IX_RefreshTokens_UserId_IsRevoked_ExpiresAt" ON "RefreshTokens" ("UserId", "IsRevoked", "ExpiresAt");


CREATE INDEX "IX_ReviewImages_ReviewId" ON "ReviewImages" ("ReviewId");


CREATE INDEX "IX_Reviews_ExpertId" ON "Reviews" ("ExpertId");


CREATE INDEX "IX_Reviews_ReviewerId" ON "Reviews" ("ReviewerId");


CREATE INDEX "IX_Reviews_SearchHireId" ON "Reviews" ("SearchHireId");


CREATE INDEX "IX_Searches_SubscriptionPlanId" ON "Searches" ("SubscriptionPlanId");


CREATE INDEX "IX_Searches_UserId" ON "Searches" ("UserId");


CREATE INDEX "IX_SearchHireDeliverables_SearchHireId" ON "SearchHireDeliverables" ("SearchHireId");


CREATE INDEX "IX_SearchHires_ClientId" ON "SearchHires" ("ClientId");


CREATE INDEX "IX_SearchHires_ExpertAvailabilityId" ON "SearchHires" ("ExpertAvailabilityId");


CREATE INDEX "IX_SearchHires_ExpertId" ON "SearchHires" ("ExpertId");


CREATE UNIQUE INDEX "IX_SearchHires_SearchId" ON "SearchHires" ("SearchId");


CREATE INDEX "IX_SearchHires_SearchServiceId" ON "SearchHires" ("SearchServiceId");


CREATE INDEX "IX_SearchHires_StatusId" ON "SearchHires" ("StatusId");


CREATE INDEX "IX_SearchParameterPlatforms_PlatformId" ON "SearchParameterPlatforms" ("PlatformId");


CREATE INDEX "IX_SearchParameters_SearchId" ON "SearchParameters" ("SearchId");


CREATE INDEX "IX_SearchParameters_ServiceTypeId" ON "SearchParameters" ("ServiceTypeId");


CREATE INDEX "IX_SearchResults_AdId" ON "SearchResults" ("AdId");


CREATE INDEX "IX_SearchResults_SearchId" ON "SearchResults" ("SearchId");


CREATE INDEX "IX_SearchResultsFiltered_AdId" ON "SearchResultsFiltered" ("AdId");


CREATE INDEX "IX_SearchResultsFiltered_SearchId" ON "SearchResultsFiltered" ("SearchId");


CREATE INDEX "IX_SearchServiceDeliverableTypes_DeliverableTypeId" ON "SearchServiceDeliverableTypes" ("DeliverableTypeId");


CREATE UNIQUE INDEX "IX_SearchServiceDeliverableTypes_SearchServiceId_DeliverableTy~" ON "SearchServiceDeliverableTypes" ("SearchServiceId", "DeliverableTypeId");


CREATE INDEX "IX_SearchServiceImages_SearchServiceId" ON "SearchServiceImages" ("SearchServiceId");


CREATE INDEX "IX_SearchServices_AIId" ON "SearchServices" ("AIId");


CREATE INDEX "IX_SearchServices_CategoryId" ON "SearchServices" ("CategoryId");


CREATE INDEX "IX_SearchServices_ExpertProfileId" ON "SearchServices" ("ExpertProfileId");


CREATE INDEX "IX_SearchServices_ServiceTypeId" ON "SearchServices" ("ServiceTypeId");


CREATE INDEX "IX_ServiceTypes_ServiceTypeCategoryId" ON "ServiceTypes" ("ServiceTypeCategoryId");


CREATE INDEX "IX_StatusConfigurations_CategoryId" ON "StatusConfigurations" ("CategoryId");


CREATE INDEX "IX_StatusConfigurations_IsActive" ON "StatusConfigurations" ("IsActive");


CREATE INDEX "IX_StatusConfigurations_ServiceTypeCategoryId" ON "StatusConfigurations" ("ServiceTypeCategoryId");


CREATE UNIQUE INDEX "IX_StatusConfigurations_StatusId_CategoryId_ServiceTypeCategor~" ON "StatusConfigurations" ("StatusId", "CategoryId", "ServiceTypeCategoryId");


CREATE INDEX "IX_StatusMappings_IsActive" ON "StatusMappings" ("IsActive");


CREATE UNIQUE INDEX "IX_StatusMappings_SourceStatusId_TargetStatusId" ON "StatusMappings" ("SourceStatusId", "TargetStatusId");


CREATE INDEX "IX_StatusMappings_TargetStatusId" ON "StatusMappings" ("TargetStatusId");


CREATE INDEX "IX_SystemSettings_AIId" ON "SystemSettings" ("AIId");


CREATE UNIQUE INDEX "IX_SystemSettings_Id" ON "SystemSettings" ("Id");


CREATE INDEX "IX_SystemStatuses_IsActive" ON "SystemStatuses" ("IsActive");


CREATE INDEX "IX_SystemStatuses_StatusType" ON "SystemStatuses" ("StatusType");


CREATE UNIQUE INDEX "IX_SystemStatuses_StatusType_StatusValue" ON "SystemStatuses" ("StatusType", "StatusValue");


CREATE UNIQUE INDEX "IX_UserMfaSettings_UserId" ON "UserMfaSettings" ("UserId");


CREATE INDEX "IX_Users_SubscriptionPlanId" ON "Users" ("SubscriptionPlanId");


CREATE INDEX "IX_UserSettings_AIId" ON "UserSettings" ("AIId");


CREATE UNIQUE INDEX "IX_UserSettings_UserId" ON "UserSettings" ("UserId");


CREATE INDEX "IX_UserSubscriptions_SubscriptionPlanId" ON "UserSubscriptions" ("SubscriptionPlanId");


CREATE INDEX "IX_UserSubscriptions_UserId" ON "UserSubscriptions" ("UserId");




-- ============================================
-- MIGRACIONES INCREMENTALES
-- ============================================

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250705190014_fixingerror') THEN
    ALTER TABLE "SearchServices" ADD "AIId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250705190014_fixingerror') THEN
    ALTER TABLE "SearchServices" ADD CONSTRAINT "FK_SearchServices_AIs_AIId" FOREIGN KEY ("AIId") REFERENCES "AIs" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250705190014_fixingerror') THEN
    CREATE INDEX "IX_SearchServices_AIId" ON "SearchServices" ("AIId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250705190014_fixingerror') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250705190014_fixingerror', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    ALTER TABLE "SearchServices" DROP CONSTRAINT "FK_SearchServices_Categories_CategoryId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE TABLE "ServiceTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_ServiceTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    INSERT INTO "ServiceTypes" ("Id", "Name", "Description", "IsActive", "CreatedAt", "UpdatedAt")
                      VALUES (1, 'Default Service', 'Default service type for existing records', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    ALTER TABLE "SearchServices" ADD "ServiceTypeId" integer NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE TABLE "Conversations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SearchHireId" integer NOT NULL,
        "ClientId" integer NOT NULL,
        "ExpertId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Conversations_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Conversations_Users_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Conversations_Users_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE TABLE "Messages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ConversationId" integer NOT NULL,
        "SenderId" integer NOT NULL,
        "Content" character varying(5000) NOT NULL,
        "SentAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "IsRead" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Messages_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_SearchServices_ServiceTypeId" ON "SearchServices" ("ServiceTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_Conversations_ClientId" ON "Conversations" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_Conversations_ExpertId" ON "Conversations" ("ExpertId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_Conversations_SearchHireId" ON "Conversations" ("SearchHireId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_Messages_ConversationId" ON "Messages" ("ConversationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    ALTER TABLE "SearchServices" ADD CONSTRAINT "FK_SearchServices_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    ALTER TABLE "SearchServices" ADD CONSTRAINT "FK_SearchServices_ServiceTypes_ServiceTypeId" FOREIGN KEY ("ServiceTypeId") REFERENCES "ServiceTypes" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250709115623_servicestypeychat', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709223005_addingsearchparameterservicd') THEN
    ALTER TABLE "SearchParameters" ADD "ServiceTypeId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709223005_addingsearchparameterservicd') THEN
    CREATE INDEX "IX_SearchParameters_ServiceTypeId" ON "SearchParameters" ("ServiceTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709223005_addingsearchparameterservicd') THEN
    ALTER TABLE "SearchParameters" ADD CONSTRAINT "FK_SearchParameters_ServiceTypes_ServiceTypeId" FOREIGN KEY ("ServiceTypeId") REFERENCES "ServiceTypes" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709223005_addingsearchparameterservicd') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250709223005_addingsearchparameterservicd', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725172014_makingnullabledurationinhours') THEN
    ALTER TABLE "SearchServices" ALTER COLUMN "DurationInHours" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725172014_makingnullabledurationinhours') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250725172014_makingnullabledurationinhours', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725175826_changingupdated') THEN
    ALTER TABLE public."SearchHires" RENAME COLUMN "CompletedAt" TO "UpdatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725175826_changingupdated') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250725175826_changingupdated', '10.0.0');
    END IF;
END $EF$;
COMMIT;
