

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE TABLE "SystemStatuses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StatusType" character varying(50) NOT NULL,
        "StatusName" character varying(50) NOT NULL,
        "StatusValue" character varying(50) NOT NULL,
        "DisplayName" character varying(100) NOT NULL,
        "Description" character varying(500),
        "IsActive" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SystemStatuses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE TABLE "StatusConfigurations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StatusId" integer NOT NULL,
        "CategoryId" integer,
        "ServiceTypeCategoryId" integer,
        "ClientPercentage" numeric NOT NULL,
        "ExpertPercentage" numeric NOT NULL,
        "PlatformPercentage" numeric NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_StatusConfigurations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StatusConfigurations_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_StatusConfigurations_ServiceTypeCategories_ServiceTypeCateg~" FOREIGN KEY ("ServiceTypeCategoryId") REFERENCES "ServiceTypeCategories" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_StatusConfigurations_SystemStatuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE TABLE "StatusMappings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SourceStatusId" integer NOT NULL,
        "TargetStatusId" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_StatusMappings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StatusMappings_SystemStatuses_SourceStatusId" FOREIGN KEY ("SourceStatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_StatusMappings_SystemStatuses_TargetStatusId" FOREIGN KEY ("TargetStatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_StatusConfigurations_CategoryId" ON "StatusConfigurations" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_StatusConfigurations_IsActive" ON "StatusConfigurations" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_StatusConfigurations_ServiceTypeCategoryId" ON "StatusConfigurations" ("ServiceTypeCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE UNIQUE INDEX "IX_StatusConfigurations_StatusId_CategoryId_ServiceTypeCategor~" ON "StatusConfigurations" ("StatusId", "CategoryId", "ServiceTypeCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_StatusMappings_IsActive" ON "StatusMappings" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE UNIQUE INDEX "IX_StatusMappings_SourceStatusId_TargetStatusId" ON "StatusMappings" ("SourceStatusId", "TargetStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_StatusMappings_TargetStatusId" ON "StatusMappings" ("TargetStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_SystemStatuses_IsActive" ON "SystemStatuses" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_SystemStatuses_StatusType" ON "SystemStatuses" ("StatusType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE UNIQUE INDEX "IX_SystemStatuses_StatusType_StatusValue" ON "SystemStatuses" ("StatusType", "StatusValue");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'Pending', 'pending', 'Pendiente', 'Contratación pendiente', TRUE, 1, TIMESTAMPTZ '2026-01-03T15:32:35.281122Z', TIMESTAMPTZ '2026-01-03T15:32:35.281123Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'AwaitingClientDecision', 'awaiting_client_decision', 'Esperando Decisión del Cliente', 'Esperando decisión del cliente', TRUE, 2, TIMESTAMPTZ '2026-01-03T15:32:35.281124Z', TIMESTAMPTZ '2026-01-03T15:32:35.281124Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'Disputed', 'disputed', 'En Disputa', 'En disputa', TRUE, 3, TIMESTAMPTZ '2026-01-03T15:32:35.281125Z', TIMESTAMPTZ '2026-01-03T15:32:35.281125Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'Completed', 'completed', 'Completado', 'Servicio completado', TRUE, 4, TIMESTAMPTZ '2026-01-03T15:32:35.281125Z', TIMESTAMPTZ '2026-01-03T15:32:35.281125Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'Cancelled', 'cancelled', 'Cancelado', 'Cancelado (genérico)', TRUE, 5, TIMESTAMPTZ '2026-01-03T15:32:35.281125Z', TIMESTAMPTZ '2026-01-03T15:32:35.281125Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'TransferFailed', 'transfer_failed', 'Transferencia Fallida', 'Transferencia fallida', TRUE, 6, TIMESTAMPTZ '2026-01-03T15:32:35.281127Z', TIMESTAMPTZ '2026-01-03T15:32:35.281127Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'DisputeResolvedClient', 'dispute_resolved_client', 'Disputa Resuelta a Favor del Cliente', 'Disputa resuelta a favor del cliente', TRUE, 7, TIMESTAMPTZ '2026-01-03T15:32:35.281127Z', TIMESTAMPTZ '2026-01-03T15:32:35.281127Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'DisputeResolvedExpert', 'dispute_resolved_expert', 'Disputa Resuelta a Favor del Experto', 'Disputa resuelta a favor del experto', TRUE, 8, TIMESTAMPTZ '2026-01-03T15:32:35.281127Z', TIMESTAMPTZ '2026-01-03T15:32:35.281127Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AwaitingAppointment', 'awaiting_appointment', 'Esperando Cita', 'Esperando propuesta del cliente (48h)', TRUE, 1, TIMESTAMPTZ '2026-01-03T15:32:35.281129Z', TIMESTAMPTZ '2026-01-03T15:32:35.281129Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentProposed', 'appointment_proposed', 'Cita Propuesta', 'Cliente propuso cita', TRUE, 2, TIMESTAMPTZ '2026-01-03T15:32:35.28113Z', TIMESTAMPTZ '2026-01-03T15:32:35.28113Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentConfirmed', 'appointment_confirmed', 'Cita Confirmada', 'Experto confirmó', TRUE, 3, TIMESTAMPTZ '2026-01-03T15:32:35.28113Z', TIMESTAMPTZ '2026-01-03T15:32:35.28113Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentRejected', 'appointment_rejected', 'Cita Rechazada', 'Experto rechazó', TRUE, 4, TIMESTAMPTZ '2026-01-03T15:32:35.28113Z', TIMESTAMPTZ '2026-01-03T15:32:35.28113Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCancelledByClient', 'appointment_cancelled_by_client', 'Cancelado por Cliente', 'Primera cancelación del cliente', TRUE, 5, TIMESTAMPTZ '2026-01-03T15:32:35.28113Z', TIMESTAMPTZ '2026-01-03T15:32:35.28113Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCancelledByClientSecond', 'appointment_cancelled_by_client_second', 'Cancelado por Cliente (Segunda)', 'Segunda cancelación del cliente', TRUE, 6, TIMESTAMPTZ '2026-01-03T15:32:35.281131Z', TIMESTAMPTZ '2026-01-03T15:32:35.281131Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCancelledByExpert', 'appointment_cancelled_by_expert', 'Cancelado por Experto', 'Experto cancela voluntariamente', TRUE, 7, TIMESTAMPTZ '2026-01-03T15:32:35.281131Z', TIMESTAMPTZ '2026-01-03T15:32:35.281132Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCancelledByNoResponse', 'appointment_cancelled_by_no_response', 'Cancelado por Falta de Respuesta', 'Cliente no propuso en tiempo', TRUE, 8, TIMESTAMPTZ '2026-01-03T15:32:35.281132Z', TIMESTAMPTZ '2026-01-03T15:32:35.281132Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCancelledByExpertRejection', 'appointment_cancelled_by_expert_rejection', 'Cancelado por Rechazo del Experto', 'Experto rechazó 2 veces', TRUE, 9, TIMESTAMPTZ '2026-01-03T15:32:35.281132Z', TIMESTAMPTZ '2026-01-03T15:32:35.281132Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCompleted', 'appointment_completed', 'Cita Completada', 'Cita realizada exitosamente', TRUE, 10, TIMESTAMPTZ '2026-01-03T15:32:35.281132Z', TIMESTAMPTZ '2026-01-03T15:32:35.281133Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN

                    INSERT INTO "StatusMappings" ("SourceStatusId", "TargetStatusId", "IsActive", "CreatedAt")
                    SELECT 
                        s1."Id" as SourceStatusId,
                        s2."Id" as TargetStatusId,
                        true as IsActive,
                        CURRENT_TIMESTAMP as CreatedAt
                    FROM "SystemStatuses" s1
                    CROSS JOIN "SystemStatuses" s2
                    WHERE s1."StatusValue" = 'appointment_completed' 
                    AND s2."StatusValue" = 'awaiting_client_decision'
                    
                    UNION ALL
                    
                    SELECT 
                        s1."Id" as SourceStatusId,
                        s2."Id" as TargetStatusId,
                        true as IsActive,
                        CURRENT_TIMESTAMP as CreatedAt
                    FROM "SystemStatuses" s1
                    CROSS JOIN "SystemStatuses" s2
                    WHERE s1."StatusValue" IN ('appointment_cancelled_by_client', 'appointment_cancelled_by_client_second', 
                                               'appointment_cancelled_by_expert', 'appointment_cancelled_by_no_response', 
                                               'appointment_cancelled_by_expert_rejection')
                    AND s2."StatusValue" = 'cancelled'
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN

                    INSERT INTO "StatusConfigurations" ("StatusId", "CategoryId", "ServiceTypeCategoryId", 
                                                       "ClientPercentage", "ExpertPercentage", "PlatformPercentage", 
                                                       "IsActive", "CreatedAt", "UpdatedAt")
                    SELECT 
                        ss."Id" as StatusId,
                        cstc."CategoryId",
                        cstc."ServiceTypeCategoryId",
                        cstc."ClientPercentage",
                        cstc."ExpertPercentage",
                        cstc."PlatformPercentage",
                        cstc."IsActive",
                        cstc."CreatedAt",
                        cstc."UpdatedAt"
                    FROM "CategoryServiceTypeConfigs" cstc
                    JOIN "SystemStatuses" ss ON ss."StatusValue" = cstc."Status"
                    WHERE cstc."Status" IN ('completed', 'dispute-resolved-client', 'dispute-resolved-expert', 'cancelled')
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    PERFORM setval(
        pg_get_serial_sequence('"SystemStatuses"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "SystemStatuses") + 1,
            nextval(pg_get_serial_sequence('"SystemStatuses"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928091555_CreateCentralizedStatusSystem', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    ALTER TABLE "Appointments" ADD "StatusId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    CREATE INDEX "IX_Appointments_StatusId" ON "Appointments" ("StatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN

                    UPDATE "Appointments" 
                    SET "StatusId" = (
                        SELECT ss."Id" 
                        FROM "SystemStatuses" ss 
                        WHERE ss."StatusType" = 'AppointmentStatus' 
                        AND ss."StatusValue" = "Appointments"."Status"
                    )
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    ALTER TABLE "Appointments" ALTER COLUMN "StatusId" SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    ALTER TABLE "Appointments" ADD CONSTRAINT "FK_Appointments_SystemStatuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    ALTER TABLE "Appointments" DROP COLUMN "Status";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928092439_OptimizeAppointmentsTable', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092539_RemoveRedundantConfigTables') THEN
    DROP TABLE "AppointmentStatusConfigs";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092539_RemoveRedundantConfigTables') THEN
    DROP TABLE "ServiceTypeCategoryConfigs";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092539_RemoveRedundantConfigTables') THEN
    DROP TABLE "CategoryServiceTypeConfigs";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092539_RemoveRedundantConfigTables') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928092539_RemoveRedundantConfigTables', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    CREATE TABLE "DeliverableTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        "DisplayName" character varying(100) NOT NULL,
        "Description" character varying(500) NOT NULL,
        "IsRequired" boolean NOT NULL DEFAULT FALSE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "SortOrder" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_DeliverableTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    CREATE TABLE "SearchHireDeliverableTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SearchHireId" integer NOT NULL,
        "DeliverableTypeId" integer NOT NULL,
        "IsSelected" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_SearchHireDeliverableTypes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SearchHireDeliverableTypes_DeliverableTypes_DeliverableType~" FOREIGN KEY ("DeliverableTypeId") REFERENCES "DeliverableTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_SearchHireDeliverableTypes_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    CREATE UNIQUE INDEX "IX_DeliverableTypes_Name" ON "DeliverableTypes" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    CREATE INDEX "IX_SearchHireDeliverableTypes_DeliverableTypeId" ON "SearchHireDeliverableTypes" ("DeliverableTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    CREATE UNIQUE INDEX "IX_SearchHireDeliverableTypes_SearchHireId_DeliverableTypeId" ON "SearchHireDeliverableTypes" ("SearchHireId", "DeliverableTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928182057_AddSearchServiceDeliverableTypes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928182057_AddSearchServiceDeliverableTypes', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928191752_InsertDeliverableTypesData') THEN
    ALTER TABLE "DeliverableTypes" ALTER COLUMN "Description" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928191752_InsertDeliverableTypesData') THEN
    CREATE TABLE "SearchServiceDeliverableTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SearchServiceId" integer NOT NULL,
        "DeliverableTypeId" integer NOT NULL,
        "IsSelected" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_SearchServiceDeliverableTypes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SearchServiceDeliverableTypes_DeliverableTypes_DeliverableT~" FOREIGN KEY ("DeliverableTypeId") REFERENCES "DeliverableTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_SearchServiceDeliverableTypes_SearchServices_SearchServiceId" FOREIGN KEY ("SearchServiceId") REFERENCES "SearchServices" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928191752_InsertDeliverableTypesData') THEN
    CREATE INDEX "IX_SearchServiceDeliverableTypes_DeliverableTypeId" ON "SearchServiceDeliverableTypes" ("DeliverableTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928191752_InsertDeliverableTypesData') THEN
    CREATE UNIQUE INDEX "IX_SearchServiceDeliverableTypes_SearchServiceId_DeliverableTy~" ON "SearchServiceDeliverableTypes" ("SearchServiceId", "DeliverableTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928191752_InsertDeliverableTypesData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928191752_InsertDeliverableTypesData', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928195229_InsertDeliverableTypesDataFinal') THEN
    DROP TABLE "SearchHireDeliverableTypes";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928195229_InsertDeliverableTypesDataFinal') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928195229_InsertDeliverableTypesDataFinal', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930092400_UpdateAppointmentStatusFlow') THEN

                    DELETE FROM "StatusMappings" 
                    WHERE "SourceStatusId" IN (
                        SELECT "Id" FROM "SystemStatuses" 
                        WHERE "StatusType" = 'AppointmentStatus' 
                        AND "StatusValue" = 'appointment_completed'
                    )
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930092400_UpdateAppointmentStatusFlow') THEN

                    DELETE FROM "SystemStatuses" 
                    WHERE "StatusType" = 'AppointmentStatus' 
                    AND "StatusValue" = 'appointment_completed'
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930092400_UpdateAppointmentStatusFlow') THEN

                    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
                    SELECT 'AppointmentStatus', 'AppointmentAwaitingReport', 'appointment_awaiting_report', 'Esperando Reporte', 'Esperando reporte/archivos del experto (3h después de la cita)', true, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    WHERE NOT EXISTS (
                        SELECT 1 FROM "SystemStatuses" 
                        WHERE "StatusType" = 'AppointmentStatus' 
                        AND "StatusValue" = 'appointment_awaiting_report'
                    )
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930092400_UpdateAppointmentStatusFlow') THEN

                    INSERT INTO "StatusMappings" ("SourceStatusId", "TargetStatusId", "IsActive", "CreatedAt")
                    SELECT 
                        s1."Id" as SourceStatusId,
                        s2."Id" as TargetStatusId,
                        true as IsActive,
                        CURRENT_TIMESTAMP as CreatedAt
                    FROM "SystemStatuses" s1
                    CROSS JOIN "SystemStatuses" s2
                    WHERE s1."StatusValue" = 'appointment_awaiting_report' 
                    AND s2."StatusValue" = 'awaiting_client_decision'
                    AND NOT EXISTS (
                        SELECT 1 FROM "StatusMappings" sm
                        WHERE sm."SourceStatusId" = s1."Id"
                        AND sm."TargetStatusId" = s2."Id"
                    )
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930092400_UpdateAppointmentStatusFlow') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250930092400_UpdateAppointmentStatusFlow', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251001112052_AddExpertReportTimeoutStatus') THEN

                    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
                    SELECT 'AppointmentStatus', 'AppointmentCancelledByNoReport', 'appointment_cancelled_by_no_report', 'Cancelada por No Reporte', 'Cita cancelada porque el experto no envió reporte en 24h', true, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    WHERE NOT EXISTS (
                        SELECT 1 FROM "SystemStatuses" 
                        WHERE "StatusType" = 'AppointmentStatus' 
                        AND "StatusValue" = 'appointment_cancelled_by_no_report'
                    )
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251001112052_AddExpertReportTimeoutStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251001112052_AddExpertReportTimeoutStatus', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251018153126_AddIsFinalizationStatusToSystemStatuses') THEN
    ALTER TABLE "SystemStatuses" ADD "IsFinalizationStatus" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251018153126_AddIsFinalizationStatusToSystemStatuses') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251018153126_AddIsFinalizationStatusToSystemStatuses', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    CREATE TABLE "LogTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "Category" character varying(50) NOT NULL,
        "Severity" character varying(20) NOT NULL,
        "RequiresAdminNotification" boolean NOT NULL,
        "RequiresEmailAlert" boolean NOT NULL,
        "RequiresSmsAlert" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LogTypes" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_LogTypes_Name" UNIQUE ("Name")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    ALTER TABLE "Logs" ADD "AdditionalData" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    ALTER TABLE "Logs" ADD "LogTypeId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    ALTER TABLE "Logs" ADD "RelatedEntityId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    ALTER TABLE "Logs" ADD "RelatedEntityType" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    CREATE INDEX "IX_Logs_LogTypeId" ON "Logs" ("LogTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    ALTER TABLE "Logs" ADD CONSTRAINT "FK_Logs_LogTypes_LogTypeId" FOREIGN KEY ("LogTypeId") REFERENCES "LogTypes" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN

                    INSERT INTO "LogTypes" ("Name", "Description", "Category", "Severity", "RequiresAdminNotification", "RequiresEmailAlert", "RequiresSmsAlert", "IsActive", "CreatedAt")
                    VALUES 
                    -- Critical Log Types
                    ('TRANSFER_FAILED', 'Transfer to expert failed but service completed', 'Critical', 'Critical', true, true, false, true, NOW()),
                    ('REFUND_FAILED', 'Automatic refund failed after payment', 'Critical', 'Critical', true, true, false, true, NOW()),
                    ('PAYMENT_PROCESSING_ERROR', 'Error processing payment in Stripe', 'Critical', 'Critical', true, true, false, true, NOW()),
                    ('STRIPE_WEBHOOK_ERROR', 'Error processing Stripe webhook', 'Critical', 'Critical', true, false, false, true, NOW()),

                    -- Error Log Types
                    ('SEARCH_CREATION_ERROR', 'Error creating search after payment', 'Error', 'High', true, false, false, true, NOW()),
                    ('EXPERT_ACCOUNT_VERIFICATION_FAILED', 'Expert account verification failed', 'Error', 'High', false, false, false, true, NOW()),
                    ('DATABASE_CONNECTION_ERROR', 'Database connection error', 'Error', 'High', true, false, false, true, NOW()),
                    ('EXTERNAL_API_ERROR', 'Error calling external API', 'Error', 'Medium', false, false, false, true, NOW()),

                    -- Warning Log Types
                    ('EXPERT_ACCOUNT_PENDING', 'Expert account pending verification', 'Warning', 'Medium', false, false, false, true, NOW()),
                    ('PAYMENT_RETRY_ATTEMPT', 'Payment retry attempt', 'Warning', 'Medium', false, false, false, true, NOW()),
                    ('USER_ACTION_LIMIT_EXCEEDED', 'User exceeded action limits', 'Warning', 'Low', false, false, false, true, NOW()),

                    -- Info Log Types
                    ('SERVICE_COMPLETED', 'Service completed successfully', 'Info', 'Low', false, false, false, true, NOW()),
                    ('REFUND_PROCESSED', 'Refund processed successfully', 'Info', 'Low', false, false, false, true, NOW()),
                    ('PAYMENT_SUCCESSFUL', 'Payment processed successfully', 'Info', 'Low', false, false, false, true, NOW()),
                    ('USER_LOGIN', 'User logged in', 'Info', 'Low', false, false, false, true, NOW()),
                    ('SEARCH_CREATED', 'Search created successfully', 'Info', 'Low', false, false, false, true, NOW()),
                    ('EXPERT_ACCOUNT_VERIFIED', 'Expert account verified', 'Info', 'Low', false, false, false, true, NOW())
                    ON CONFLICT ("Name") DO NOTHING;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251019224616_AddLogTypeTableOnly', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "Logs" DROP CONSTRAINT "FK_Logs_LogTypes_LogTypeId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    CREATE TABLE "Severities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(20) NOT NULL,
        "Description" character varying(100),
        "SortOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Severities" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    CREATE UNIQUE INDEX "IX_Severities_Name" ON "Severities" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN

                    INSERT INTO "Severities" ("Name", "Description", "SortOrder", "IsActive", "CreatedAt")
                    VALUES
                    ('Critical', 'Critical severity level', 1, true, NOW()),
                    ('High', 'High severity level', 2, true, NOW()),
                    ('Medium', 'Medium severity level', 3, true, NOW()),
                    ('Low', 'Low severity level', 4, true, NOW())
                    ON CONFLICT ("Name") DO NOTHING;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "LogTypes" ADD "SeverityId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN

                    UPDATE "LogTypes" 
                    SET "SeverityId" = (
                        CASE 
                            WHEN "Severity" = 'Critical' THEN (SELECT "Id" FROM "Severities" WHERE "Name" = 'Critical')
                            WHEN "Severity" = 'High' THEN (SELECT "Id" FROM "Severities" WHERE "Name" = 'High')
                            WHEN "Severity" = 'Medium' THEN (SELECT "Id" FROM "Severities" WHERE "Name" = 'Medium')
                            WHEN "Severity" = 'Low' THEN (SELECT "Id" FROM "Severities" WHERE "Name" = 'Low')
                            ELSE (SELECT "Id" FROM "Severities" WHERE "Name" = 'Low')
                        END
                    )
                    WHERE "SeverityId" IS NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "LogTypes" ALTER COLUMN "SeverityId" SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "LogTypes" DROP COLUMN "Severity";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    CREATE INDEX "IX_LogTypes_SeverityId" ON "LogTypes" ("SeverityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "Logs" ADD CONSTRAINT "FK_Logs_LogTypes_LogTypeId" FOREIGN KEY ("LogTypeId") REFERENCES "LogTypes" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "LogTypes" ADD CONSTRAINT "FK_LogTypes_Severities_SeverityId" FOREIGN KEY ("SeverityId") REFERENCES "Severities" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251019230221_AddSeverityTableAndUpdateLogType', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" DROP CONSTRAINT "FK_LogTypes_Severities_SeverityId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" DROP COLUMN "Category";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" ALTER COLUMN "SeverityId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" ALTER COLUMN "Name" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" ALTER COLUMN "Description" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" ADD CONSTRAINT "FK_LogTypes_Severities_SeverityId" FOREIGN KEY ("SeverityId") REFERENCES "Severities" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251019231824_SimplifyLogTypes', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019234253_RemoveLogLevelColumn') THEN
    ALTER TABLE "Logs" DROP COLUMN "LogLevel";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019234253_RemoveLogLevelColumn') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251019234253_RemoveLogLevelColumn', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103652_AddSeparateCancellationCounters') THEN
    ALTER TABLE "Appointments" ADD "ClientCancellationCount" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103652_AddSeparateCancellationCounters') THEN
    ALTER TABLE "Appointments" ADD "ExpertCancellationCount" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103652_AddSeparateCancellationCounters') THEN
    ALTER TABLE "Appointments" ADD "LastClientCancellationAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103652_AddSeparateCancellationCounters') THEN
    ALTER TABLE "Appointments" ADD "LastExpertCancellationAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103652_AddSeparateCancellationCounters') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021103652_AddSeparateCancellationCounters', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103829_RemoveGlobalCancellationCount') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021103829_RemoveGlobalCancellationCount', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251028122232_AddColorToSystemStatuses') THEN
    ALTER TABLE "Appointments" DROP COLUMN "CancellationCount";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251028122232_AddColorToSystemStatuses') THEN
    ALTER TABLE "SystemStatuses" ADD "Color" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251028122232_AddColorToSystemStatuses') THEN
    ALTER TABLE "Appointments" ALTER COLUMN "ExpertCancellationCount" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251028122232_AddColorToSystemStatuses') THEN
    ALTER TABLE "Appointments" ALTER COLUMN "ClientCancellationCount" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251028122232_AddColorToSystemStatuses') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251028122232_AddColorToSystemStatuses', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    ALTER TABLE "SearchHires" ADD "ExpertAvailabilityId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    CREATE TABLE "ExpertAvailabilities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ExpertId" integer NOT NULL,
        "DaysOfWeek" text NOT NULL,
        "StartTime" interval NOT NULL,
        "EndTime" interval NOT NULL,
        "EffectiveFrom" timestamp with time zone NOT NULL,
        "EffectiveTo" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ExpertAvailabilities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExpertAvailabilities_ExpertProfiles_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "ExpertProfiles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    CREATE INDEX "IX_SearchHires_ExpertAvailabilityId" ON "SearchHires" ("ExpertAvailabilityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    CREATE INDEX "IX_ExpertAvailabilities_ExpertId_IsActive_EffectiveTo" ON "ExpertAvailabilities" ("ExpertId", "IsActive", "EffectiveTo") WHERE "EffectiveTo" IS NULL AND "IsActive" = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    ALTER TABLE "SearchHires" ADD CONSTRAINT "FK_SearchHires_ExpertAvailabilities_ExpertAvailabilityId" FOREIGN KEY ("ExpertAvailabilityId") REFERENCES "ExpertAvailabilities" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251101025058_AddExpertAvailabilitySystem', '10.0.0');
    END IF;
END $EF$;
COMMIT;
