

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE TABLE "SystemStatuses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StatusType" character varying(50) NOT NULL,
        "StatusName" character varying(50) NOT NULL,
        "StatusValue" character varying(50) NOT NULL,
        "DisplayName" character varying(100) NOT NULL,
        "Description" character varying(500),
        "IsActive" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SystemStatuses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE TABLE "StatusConfigurations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StatusId" integer NOT NULL,
        "CategoryId" integer,
        "ServiceTypeCategoryId" integer,
        "ClientPercentage" numeric NOT NULL,
        "ExpertPercentage" numeric NOT NULL,
        "PlatformPercentage" numeric NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_StatusConfigurations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StatusConfigurations_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_StatusConfigurations_ServiceTypeCategories_ServiceTypeCateg~" FOREIGN KEY ("ServiceTypeCategoryId") REFERENCES "ServiceTypeCategories" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_StatusConfigurations_SystemStatuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE TABLE "StatusMappings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SourceStatusId" integer NOT NULL,
        "TargetStatusId" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_StatusMappings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StatusMappings_SystemStatuses_SourceStatusId" FOREIGN KEY ("SourceStatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_StatusMappings_SystemStatuses_TargetStatusId" FOREIGN KEY ("TargetStatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_StatusConfigurations_CategoryId" ON "StatusConfigurations" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_StatusConfigurations_IsActive" ON "StatusConfigurations" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_StatusConfigurations_ServiceTypeCategoryId" ON "StatusConfigurations" ("ServiceTypeCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE UNIQUE INDEX "IX_StatusConfigurations_StatusId_CategoryId_ServiceTypeCategor~" ON "StatusConfigurations" ("StatusId", "CategoryId", "ServiceTypeCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_StatusMappings_IsActive" ON "StatusMappings" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE UNIQUE INDEX "IX_StatusMappings_SourceStatusId_TargetStatusId" ON "StatusMappings" ("SourceStatusId", "TargetStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_StatusMappings_TargetStatusId" ON "StatusMappings" ("TargetStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_SystemStatuses_IsActive" ON "SystemStatuses" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE INDEX "IX_SystemStatuses_StatusType" ON "SystemStatuses" ("StatusType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    CREATE UNIQUE INDEX "IX_SystemStatuses_StatusType_StatusValue" ON "SystemStatuses" ("StatusType", "StatusValue");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'Pending', 'pending', 'Pendiente', 'Contratación pendiente', TRUE, 1, TIMESTAMPTZ '2026-01-03T15:32:35.281122Z', TIMESTAMPTZ '2026-01-03T15:32:35.281123Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'AwaitingClientDecision', 'awaiting_client_decision', 'Esperando Decisión del Cliente', 'Esperando decisión del cliente', TRUE, 2, TIMESTAMPTZ '2026-01-03T15:32:35.281124Z', TIMESTAMPTZ '2026-01-03T15:32:35.281124Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'Disputed', 'disputed', 'En Disputa', 'En disputa', TRUE, 3, TIMESTAMPTZ '2026-01-03T15:32:35.281125Z', TIMESTAMPTZ '2026-01-03T15:32:35.281125Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'Completed', 'completed', 'Completado', 'Servicio completado', TRUE, 4, TIMESTAMPTZ '2026-01-03T15:32:35.281125Z', TIMESTAMPTZ '2026-01-03T15:32:35.281125Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'Cancelled', 'cancelled', 'Cancelado', 'Cancelado (genérico)', TRUE, 5, TIMESTAMPTZ '2026-01-03T15:32:35.281125Z', TIMESTAMPTZ '2026-01-03T15:32:35.281125Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'TransferFailed', 'transfer_failed', 'Transferencia Fallida', 'Transferencia fallida', TRUE, 6, TIMESTAMPTZ '2026-01-03T15:32:35.281127Z', TIMESTAMPTZ '2026-01-03T15:32:35.281127Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'DisputeResolvedClient', 'dispute_resolved_client', 'Disputa Resuelta a Favor del Cliente', 'Disputa resuelta a favor del cliente', TRUE, 7, TIMESTAMPTZ '2026-01-03T15:32:35.281127Z', TIMESTAMPTZ '2026-01-03T15:32:35.281127Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('SearchHireStatus', 'DisputeResolvedExpert', 'dispute_resolved_expert', 'Disputa Resuelta a Favor del Experto', 'Disputa resuelta a favor del experto', TRUE, 8, TIMESTAMPTZ '2026-01-03T15:32:35.281127Z', TIMESTAMPTZ '2026-01-03T15:32:35.281127Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AwaitingAppointment', 'awaiting_appointment', 'Esperando Cita', 'Esperando propuesta del cliente (48h)', TRUE, 1, TIMESTAMPTZ '2026-01-03T15:32:35.281129Z', TIMESTAMPTZ '2026-01-03T15:32:35.281129Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentProposed', 'appointment_proposed', 'Cita Propuesta', 'Cliente propuso cita', TRUE, 2, TIMESTAMPTZ '2026-01-03T15:32:35.28113Z', TIMESTAMPTZ '2026-01-03T15:32:35.28113Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentConfirmed', 'appointment_confirmed', 'Cita Confirmada', 'Experto confirmó', TRUE, 3, TIMESTAMPTZ '2026-01-03T15:32:35.28113Z', TIMESTAMPTZ '2026-01-03T15:32:35.28113Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentRejected', 'appointment_rejected', 'Cita Rechazada', 'Experto rechazó', TRUE, 4, TIMESTAMPTZ '2026-01-03T15:32:35.28113Z', TIMESTAMPTZ '2026-01-03T15:32:35.28113Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCancelledByClient', 'appointment_cancelled_by_client', 'Cancelado por Cliente', 'Primera cancelación del cliente', TRUE, 5, TIMESTAMPTZ '2026-01-03T15:32:35.28113Z', TIMESTAMPTZ '2026-01-03T15:32:35.28113Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCancelledByClientSecond', 'appointment_cancelled_by_client_second', 'Cancelado por Cliente (Segunda)', 'Segunda cancelación del cliente', TRUE, 6, TIMESTAMPTZ '2026-01-03T15:32:35.281131Z', TIMESTAMPTZ '2026-01-03T15:32:35.281131Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCancelledByExpert', 'appointment_cancelled_by_expert', 'Cancelado por Experto', 'Experto cancela voluntariamente', TRUE, 7, TIMESTAMPTZ '2026-01-03T15:32:35.281131Z', TIMESTAMPTZ '2026-01-03T15:32:35.281132Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCancelledByNoResponse', 'appointment_cancelled_by_no_response', 'Cancelado por Falta de Respuesta', 'Cliente no propuso en tiempo', TRUE, 8, TIMESTAMPTZ '2026-01-03T15:32:35.281132Z', TIMESTAMPTZ '2026-01-03T15:32:35.281132Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCancelledByExpertRejection', 'appointment_cancelled_by_expert_rejection', 'Cancelado por Rechazo del Experto', 'Experto rechazó 2 veces', TRUE, 9, TIMESTAMPTZ '2026-01-03T15:32:35.281132Z', TIMESTAMPTZ '2026-01-03T15:32:35.281132Z');
    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
    VALUES ('AppointmentStatus', 'AppointmentCompleted', 'appointment_completed', 'Cita Completada', 'Cita realizada exitosamente', TRUE, 10, TIMESTAMPTZ '2026-01-03T15:32:35.281132Z', TIMESTAMPTZ '2026-01-03T15:32:35.281133Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN

                    INSERT INTO "StatusMappings" ("SourceStatusId", "TargetStatusId", "IsActive", "CreatedAt")
                    SELECT 
                        s1."Id" as SourceStatusId,
                        s2."Id" as TargetStatusId,
                        true as IsActive,
                        CURRENT_TIMESTAMP as CreatedAt
                    FROM "SystemStatuses" s1
                    CROSS JOIN "SystemStatuses" s2
                    WHERE s1."StatusValue" = 'appointment_completed' 
                    AND s2."StatusValue" = 'awaiting_client_decision'
                    
                    UNION ALL
                    
                    SELECT 
                        s1."Id" as SourceStatusId,
                        s2."Id" as TargetStatusId,
                        true as IsActive,
                        CURRENT_TIMESTAMP as CreatedAt
                    FROM "SystemStatuses" s1
                    CROSS JOIN "SystemStatuses" s2
                    WHERE s1."StatusValue" IN ('appointment_cancelled_by_client', 'appointment_cancelled_by_client_second', 
                                               'appointment_cancelled_by_expert', 'appointment_cancelled_by_no_response', 
                                               'appointment_cancelled_by_expert_rejection')
                    AND s2."StatusValue" = 'cancelled'
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN

                    INSERT INTO "StatusConfigurations" ("StatusId", "CategoryId", "ServiceTypeCategoryId", 
                                                       "ClientPercentage", "ExpertPercentage", "PlatformPercentage", 
                                                       "IsActive", "CreatedAt", "UpdatedAt")
                    SELECT 
                        ss."Id" as StatusId,
                        cstc."CategoryId",
                        cstc."ServiceTypeCategoryId",
                        cstc."ClientPercentage",
                        cstc."ExpertPercentage",
                        cstc."PlatformPercentage",
                        cstc."IsActive",
                        cstc."CreatedAt",
                        cstc."UpdatedAt"
                    FROM "CategoryServiceTypeConfigs" cstc
                    JOIN "SystemStatuses" ss ON ss."StatusValue" = cstc."Status"
                    WHERE cstc."Status" IN ('completed', 'dispute-resolved-client', 'dispute-resolved-expert', 'cancelled')
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    PERFORM setval(
        pg_get_serial_sequence('"SystemStatuses"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "SystemStatuses") + 1,
            nextval(pg_get_serial_sequence('"SystemStatuses"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928091555_CreateCentralizedStatusSystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928091555_CreateCentralizedStatusSystem', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    ALTER TABLE "Appointments" ADD "StatusId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    CREATE INDEX "IX_Appointments_StatusId" ON "Appointments" ("StatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN

                    UPDATE "Appointments" 
                    SET "StatusId" = (
                        SELECT ss."Id" 
                        FROM "SystemStatuses" ss 
                        WHERE ss."StatusType" = 'AppointmentStatus' 
                        AND ss."StatusValue" = "Appointments"."Status"
                    )
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    ALTER TABLE "Appointments" ALTER COLUMN "StatusId" SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    ALTER TABLE "Appointments" ADD CONSTRAINT "FK_Appointments_SystemStatuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "SystemStatuses" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    ALTER TABLE "Appointments" DROP COLUMN "Status";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092439_OptimizeAppointmentsTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928092439_OptimizeAppointmentsTable', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092539_RemoveRedundantConfigTables') THEN
    DROP TABLE "AppointmentStatusConfigs";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092539_RemoveRedundantConfigTables') THEN
    DROP TABLE "ServiceTypeCategoryConfigs";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092539_RemoveRedundantConfigTables') THEN
    DROP TABLE "CategoryServiceTypeConfigs";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928092539_RemoveRedundantConfigTables') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928092539_RemoveRedundantConfigTables', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    CREATE TABLE "DeliverableTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        "DisplayName" character varying(100) NOT NULL,
        "Description" character varying(500) NOT NULL,
        "IsRequired" boolean NOT NULL DEFAULT FALSE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "SortOrder" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_DeliverableTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    CREATE TABLE "SearchHireDeliverableTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SearchHireId" integer NOT NULL,
        "DeliverableTypeId" integer NOT NULL,
        "IsSelected" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_SearchHireDeliverableTypes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SearchHireDeliverableTypes_DeliverableTypes_DeliverableType~" FOREIGN KEY ("DeliverableTypeId") REFERENCES "DeliverableTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_SearchHireDeliverableTypes_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    CREATE UNIQUE INDEX "IX_DeliverableTypes_Name" ON "DeliverableTypes" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    CREATE INDEX "IX_SearchHireDeliverableTypes_DeliverableTypeId" ON "SearchHireDeliverableTypes" ("DeliverableTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    CREATE UNIQUE INDEX "IX_SearchHireDeliverableTypes_SearchHireId_DeliverableTypeId" ON "SearchHireDeliverableTypes" ("SearchHireId", "DeliverableTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928174443_AddDeliverableTypesAndAppointmentAwaitingReportStatus', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928182057_AddSearchServiceDeliverableTypes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928182057_AddSearchServiceDeliverableTypes', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928191752_InsertDeliverableTypesData') THEN
    ALTER TABLE "DeliverableTypes" ALTER COLUMN "Description" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928191752_InsertDeliverableTypesData') THEN
    CREATE TABLE "SearchServiceDeliverableTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SearchServiceId" integer NOT NULL,
        "DeliverableTypeId" integer NOT NULL,
        "IsSelected" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_SearchServiceDeliverableTypes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SearchServiceDeliverableTypes_DeliverableTypes_DeliverableT~" FOREIGN KEY ("DeliverableTypeId") REFERENCES "DeliverableTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_SearchServiceDeliverableTypes_SearchServices_SearchServiceId" FOREIGN KEY ("SearchServiceId") REFERENCES "SearchServices" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928191752_InsertDeliverableTypesData') THEN
    CREATE INDEX "IX_SearchServiceDeliverableTypes_DeliverableTypeId" ON "SearchServiceDeliverableTypes" ("DeliverableTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928191752_InsertDeliverableTypesData') THEN
    CREATE UNIQUE INDEX "IX_SearchServiceDeliverableTypes_SearchServiceId_DeliverableTy~" ON "SearchServiceDeliverableTypes" ("SearchServiceId", "DeliverableTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928191752_InsertDeliverableTypesData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928191752_InsertDeliverableTypesData', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928195229_InsertDeliverableTypesDataFinal') THEN
    DROP TABLE "SearchHireDeliverableTypes";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250928195229_InsertDeliverableTypesDataFinal') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250928195229_InsertDeliverableTypesDataFinal', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930092400_UpdateAppointmentStatusFlow') THEN

                    DELETE FROM "StatusMappings" 
                    WHERE "SourceStatusId" IN (
                        SELECT "Id" FROM "SystemStatuses" 
                        WHERE "StatusType" = 'AppointmentStatus' 
                        AND "StatusValue" = 'appointment_completed'
                    )
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930092400_UpdateAppointmentStatusFlow') THEN

                    DELETE FROM "SystemStatuses" 
                    WHERE "StatusType" = 'AppointmentStatus' 
                    AND "StatusValue" = 'appointment_completed'
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930092400_UpdateAppointmentStatusFlow') THEN

                    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
                    SELECT 'AppointmentStatus', 'AppointmentAwaitingReport', 'appointment_awaiting_report', 'Esperando Reporte', 'Esperando reporte/archivos del experto (3h después de la cita)', true, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    WHERE NOT EXISTS (
                        SELECT 1 FROM "SystemStatuses" 
                        WHERE "StatusType" = 'AppointmentStatus' 
                        AND "StatusValue" = 'appointment_awaiting_report'
                    )
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930092400_UpdateAppointmentStatusFlow') THEN

                    INSERT INTO "StatusMappings" ("SourceStatusId", "TargetStatusId", "IsActive", "CreatedAt")
                    SELECT 
                        s1."Id" as SourceStatusId,
                        s2."Id" as TargetStatusId,
                        true as IsActive,
                        CURRENT_TIMESTAMP as CreatedAt
                    FROM "SystemStatuses" s1
                    CROSS JOIN "SystemStatuses" s2
                    WHERE s1."StatusValue" = 'appointment_awaiting_report' 
                    AND s2."StatusValue" = 'awaiting_client_decision'
                    AND NOT EXISTS (
                        SELECT 1 FROM "StatusMappings" sm
                        WHERE sm."SourceStatusId" = s1."Id"
                        AND sm."TargetStatusId" = s2."Id"
                    )
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250930092400_UpdateAppointmentStatusFlow') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250930092400_UpdateAppointmentStatusFlow', '10.0.0');
    END IF;
END $EF$;
COMMIT;
