CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250705190014_fixingerror') THEN
    ALTER TABLE "SearchServices" ADD "AIId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250705190014_fixingerror') THEN
    ALTER TABLE "SearchServices" ADD CONSTRAINT "FK_SearchServices_AIs_AIId" FOREIGN KEY ("AIId") REFERENCES "AIs" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250705190014_fixingerror') THEN
    CREATE INDEX "IX_SearchServices_AIId" ON "SearchServices" ("AIId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250705190014_fixingerror') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250705190014_fixingerror', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    ALTER TABLE "SearchServices" DROP CONSTRAINT "FK_SearchServices_Categories_CategoryId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE TABLE "ServiceTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_ServiceTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    INSERT INTO "ServiceTypes" ("Id", "Name", "Description", "IsActive", "CreatedAt", "UpdatedAt")
                      VALUES (1, 'Default Service', 'Default service type for existing records', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    ALTER TABLE "SearchServices" ADD "ServiceTypeId" integer NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE TABLE "Conversations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SearchHireId" integer NOT NULL,
        "ClientId" integer NOT NULL,
        "ExpertId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Conversations_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Conversations_Users_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Conversations_Users_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE TABLE "Messages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ConversationId" integer NOT NULL,
        "SenderId" integer NOT NULL,
        "Content" character varying(5000) NOT NULL,
        "SentAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "IsRead" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Messages_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_SearchServices_ServiceTypeId" ON "SearchServices" ("ServiceTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_Conversations_ClientId" ON "Conversations" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_Conversations_ExpertId" ON "Conversations" ("ExpertId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_Conversations_SearchHireId" ON "Conversations" ("SearchHireId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_Messages_ConversationId" ON "Messages" ("ConversationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    ALTER TABLE "SearchServices" ADD CONSTRAINT "FK_SearchServices_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    ALTER TABLE "SearchServices" ADD CONSTRAINT "FK_SearchServices_ServiceTypes_ServiceTypeId" FOREIGN KEY ("ServiceTypeId") REFERENCES "ServiceTypes" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709115623_servicestypeychat') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250709115623_servicestypeychat', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709223005_addingsearchparameterservicd') THEN
    ALTER TABLE "SearchParameters" ADD "ServiceTypeId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709223005_addingsearchparameterservicd') THEN
    CREATE INDEX "IX_SearchParameters_ServiceTypeId" ON "SearchParameters" ("ServiceTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709223005_addingsearchparameterservicd') THEN
    ALTER TABLE "SearchParameters" ADD CONSTRAINT "FK_SearchParameters_ServiceTypes_ServiceTypeId" FOREIGN KEY ("ServiceTypeId") REFERENCES "ServiceTypes" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250709223005_addingsearchparameterservicd') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250709223005_addingsearchparameterservicd', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725172014_makingnullabledurationinhours') THEN
    ALTER TABLE "SearchServices" ALTER COLUMN "DurationInHours" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725172014_makingnullabledurationinhours') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250725172014_makingnullabledurationinhours', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725175826_changingupdated') THEN
    ALTER TABLE public."SearchHires" RENAME COLUMN "CompletedAt" TO "UpdatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725175826_changingupdated') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250725175826_changingupdated', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725183643_addubicationtoexpert') THEN
    ALTER TABLE "ExpertProfiles" ADD "Latitude" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725183643_addubicationtoexpert') THEN
    ALTER TABLE "ExpertProfiles" ADD "Longitude" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725183643_addubicationtoexpert') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250725183643_addubicationtoexpert', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250729115031_changingdecimaltostring') THEN
    ALTER TABLE "ExpertProfiles" ALTER COLUMN "Longitude" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250729115031_changingdecimaltostring') THEN
    ALTER TABLE "ExpertProfiles" ALTER COLUMN "Latitude" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250729115031_changingdecimaltostring') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250729115031_changingdecimaltostring', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817142000_addingreportsandchatimagesandmaps') THEN
    ALTER TABLE "Messages" ADD "LocationLatitude" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817142000_addingreportsandchatimagesandmaps') THEN
    ALTER TABLE "Messages" ADD "LocationLongitude" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817142000_addingreportsandchatimagesandmaps') THEN
    CREATE TABLE "MessageAttachments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MessageId" integer NOT NULL,
        "Url" character varying(500) NOT NULL,
        "ObjectName" character varying(200) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MessageAttachments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MessageAttachments_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817142000_addingreportsandchatimagesandmaps') THEN
    CREATE TABLE "SearchHireDeliverables" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SearchHireId" integer NOT NULL,
        "Url" character varying(500) NOT NULL,
        "ObjectName" character varying(200) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SearchHireDeliverables" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SearchHireDeliverables_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817142000_addingreportsandchatimagesandmaps') THEN
    CREATE INDEX "IX_MessageAttachments_MessageId" ON "MessageAttachments" ("MessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817142000_addingreportsandchatimagesandmaps') THEN
    CREATE INDEX "IX_SearchHireDeliverables_SearchHireId" ON "SearchHireDeliverables" ("SearchHireId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817142000_addingreportsandchatimagesandmaps') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250817142000_addingreportsandchatimagesandmaps', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817154443_makingnull') THEN
    ALTER TABLE "Messages" ALTER COLUMN "Content" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817154443_makingnull') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250817154443_makingnull', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817154636_makingnul') THEN
    ALTER TABLE "Messages" ALTER COLUMN "Content" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250817154636_makingnul') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250817154636_makingnul', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250826183040_isactivetoservice') THEN
    ALTER TABLE "SearchServices" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250826183040_isactivetoservice') THEN
    ALTER TABLE "Messages" ALTER COLUMN "Content" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250826183040_isactivetoservice') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250826183040_isactivetoservice', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250910123846_AddOnboardingFields') THEN
    ALTER TABLE "ExpertProfiles" ADD "OnboardingCompleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250910123846_AddOnboardingFields') THEN
    ALTER TABLE "ExpertProfiles" ADD "PendingStripeAccountId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250910123846_AddOnboardingFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250910123846_AddOnboardingFields', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250910182516_AddStatusExpert') THEN
    ALTER TABLE "ExpertProfiles" ADD "StripeStatus" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250910182516_AddStatusExpert') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250910182516_AddStatusExpert', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250913104804_webhookeventlog') THEN
    CREATE TABLE "ProcessedWebhookEvents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EventId" character varying(255) NOT NULL,
        "EventType" character varying(100) NOT NULL,
        "StripeAccountId" character varying(255),
        "UserId" integer,
        "ProcessedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "Status" character varying(50) NOT NULL DEFAULT 'Success',
        "ErrorMessage" text,
        "EventData" text,
        CONSTRAINT "PK_ProcessedWebhookEvents" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250913104804_webhookeventlog') THEN
    CREATE UNIQUE INDEX "IX_ProcessedWebhookEvents_EventId" ON "ProcessedWebhookEvents" ("EventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250913104804_webhookeventlog') THEN
    CREATE INDEX "IX_ProcessedWebhookEvents_StripeAccountId" ON "ProcessedWebhookEvents" ("StripeAccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250913104804_webhookeventlog') THEN
    CREATE INDEX "IX_ProcessedWebhookEvents_UserId" ON "ProcessedWebhookEvents" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250913104804_webhookeventlog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250913104804_webhookeventlog', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250913105710_stripedetailstatus') THEN
    ALTER TABLE "ExpertProfiles" ADD "StripeStatusDetails" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250913105710_stripedetailstatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250913105710_stripedetailstatus', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250916185604_AddVacationModeToExpertProfile') THEN
    ALTER TABLE "ExpertProfiles" ADD "IsOnVacation" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250916185604_AddVacationModeToExpertProfile') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250916185604_AddVacationModeToExpertProfile', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917172538_FinancialTransactiosnUpdate') THEN
    ALTER TABLE "FinancialTransactions" ADD "StripeTransferId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917172538_FinancialTransactiosnUpdate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250917172538_FinancialTransactiosnUpdate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917173736_AddPositionToServiceType') THEN
    ALTER TABLE "ServiceTypes" ADD "Position" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917173736_AddPositionToServiceType') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250917173736_AddPositionToServiceType', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917181131_AddServiceTypeCategoryTable') THEN
    CREATE TABLE "ServiceTypeCategories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500) NOT NULL,
        "Position" integer NOT NULL DEFAULT 0,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_ServiceTypeCategories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917181131_AddServiceTypeCategoryTable') THEN
    INSERT INTO "ServiceTypeCategories" ("Id", "Name", "Description", "Position", "IsActive", "CreatedAt", "UpdatedAt")
    VALUES (1, 'Búsqueda + Revisión', 'Servicio completo de búsqueda y revisión', 1, TRUE, TIMESTAMPTZ '2026-01-03T15:32:34.331977Z', TIMESTAMPTZ '2026-01-03T15:32:34.331978Z');
    INSERT INTO "ServiceTypeCategories" ("Id", "Name", "Description", "Position", "IsActive", "CreatedAt", "UpdatedAt")
    VALUES (2, 'Revisión', 'Solo revisión presencial', 2, TRUE, TIMESTAMPTZ '2026-01-03T15:32:34.331978Z', TIMESTAMPTZ '2026-01-03T15:32:34.331978Z');
    INSERT INTO "ServiceTypeCategories" ("Id", "Name", "Description", "Position", "IsActive", "CreatedAt", "UpdatedAt")
    VALUES (3, 'Búsqueda', 'Solo búsqueda web', 3, TRUE, TIMESTAMPTZ '2026-01-03T15:32:34.331978Z', TIMESTAMPTZ '2026-01-03T15:32:34.331978Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917181131_AddServiceTypeCategoryTable') THEN
    ALTER TABLE "ServiceTypes" ADD "ServiceTypeCategoryId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917181131_AddServiceTypeCategoryTable') THEN
    ALTER TABLE "ServiceTypes" ADD CONSTRAINT "FK_ServiceTypes_ServiceTypeCategories_ServiceTypeCategoryId" FOREIGN KEY ("ServiceTypeCategoryId") REFERENCES "ServiceTypeCategories" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917181131_AddServiceTypeCategoryTable') THEN
    PERFORM setval(
        pg_get_serial_sequence('"ServiceTypeCategories"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "ServiceTypeCategories") + 1,
            nextval(pg_get_serial_sequence('"ServiceTypeCategories"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917181131_AddServiceTypeCategoryTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250917181131_AddServiceTypeCategoryTable', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    ALTER TABLE "ServiceTypes" ALTER COLUMN "ServiceTypeCategoryId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    CREATE TABLE "Appointments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SearchHireId" integer NOT NULL,
        "Status" character varying(50) NOT NULL DEFAULT 'awaiting_appointment',
        "ProposedDate" timestamp with time zone NOT NULL,
        "ProposedTime" interval NOT NULL,
        "Location" character varying(500) NOT NULL,
        "Latitude" numeric,
        "Longitude" numeric,
        "DisputeReason" text,
        "CompletedAt" timestamp with time zone,
        "CompletedBy" integer,
        "RejectionCount" integer NOT NULL DEFAULT 0,
        "CancellationCount" integer NOT NULL DEFAULT 0,
        "LastRejectionAt" timestamp with time zone,
        "LastProposalAt" timestamp with time zone,
        "LastResponseAt" timestamp with time zone,
        "IsLocked" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Appointments_SearchHires_SearchHireId" FOREIGN KEY ("SearchHireId") REFERENCES "SearchHires" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    CREATE TABLE "AppointmentTimers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppointmentId" integer NOT NULL,
        "TimerType" character varying(50) NOT NULL,
        "StartTime" timestamp with time zone NOT NULL,
        "EndTime" timestamp with time zone NOT NULL,
        "IsExpired" boolean NOT NULL DEFAULT FALSE,
        "ExpiredAt" timestamp with time zone,
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_AppointmentTimers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AppointmentTimers_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    CREATE INDEX "IX_Appointments_ProposedDate" ON "Appointments" ("ProposedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    CREATE UNIQUE INDEX "IX_Appointments_SearchHireId" ON "Appointments" ("SearchHireId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    CREATE INDEX "IX_Appointments_Status" ON "Appointments" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    CREATE INDEX "IX_AppointmentTimers_AppointmentId" ON "AppointmentTimers" ("AppointmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    CREATE INDEX "IX_AppointmentTimers_EndTime" ON "AppointmentTimers" ("EndTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    CREATE INDEX "IX_AppointmentTimers_IsExpired" ON "AppointmentTimers" ("IsExpired");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    CREATE INDEX "IX_AppointmentTimers_TimerType" ON "AppointmentTimers" ("TimerType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200411_AddAppointmentSystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250917200411_AddAppointmentSystem', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918190551_AddRequiresAppointmentToServiceType') THEN
    ALTER TABLE "ServiceTypes" ADD "RequiresAppointment" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918190551_AddRequiresAppointmentToServiceType') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250918190551_AddRequiresAppointmentToServiceType', '10.0.0');
    END IF;
END $EF$;
COMMIT;
