

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251001112052_AddExpertReportTimeoutStatus') THEN

                    INSERT INTO "SystemStatuses" ("StatusType", "StatusName", "StatusValue", "DisplayName", "Description", "IsActive", "SortOrder", "CreatedAt", "UpdatedAt")
                    SELECT 'AppointmentStatus', 'AppointmentCancelledByNoReport', 'appointment_cancelled_by_no_report', 'Cancelada por No Reporte', 'Cita cancelada porque el experto no envió reporte en 24h', true, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    WHERE NOT EXISTS (
                        SELECT 1 FROM "SystemStatuses" 
                        WHERE "StatusType" = 'AppointmentStatus' 
                        AND "StatusValue" = 'appointment_cancelled_by_no_report'
                    )
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251001112052_AddExpertReportTimeoutStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251001112052_AddExpertReportTimeoutStatus', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251018153126_AddIsFinalizationStatusToSystemStatuses') THEN
    ALTER TABLE "SystemStatuses" ADD "IsFinalizationStatus" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251018153126_AddIsFinalizationStatusToSystemStatuses') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251018153126_AddIsFinalizationStatusToSystemStatuses', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    CREATE TABLE "LogTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "Category" character varying(50) NOT NULL,
        "Severity" character varying(20) NOT NULL,
        "RequiresAdminNotification" boolean NOT NULL,
        "RequiresEmailAlert" boolean NOT NULL,
        "RequiresSmsAlert" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LogTypes" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_LogTypes_Name" UNIQUE ("Name")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    ALTER TABLE "Logs" ADD "AdditionalData" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    ALTER TABLE "Logs" ADD "LogTypeId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    ALTER TABLE "Logs" ADD "RelatedEntityId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    ALTER TABLE "Logs" ADD "RelatedEntityType" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    CREATE INDEX "IX_Logs_LogTypeId" ON "Logs" ("LogTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    ALTER TABLE "Logs" ADD CONSTRAINT "FK_Logs_LogTypes_LogTypeId" FOREIGN KEY ("LogTypeId") REFERENCES "LogTypes" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN

                    INSERT INTO "LogTypes" ("Name", "Description", "Category", "Severity", "RequiresAdminNotification", "RequiresEmailAlert", "RequiresSmsAlert", "IsActive", "CreatedAt")
                    VALUES 
                    -- Critical Log Types
                    ('TRANSFER_FAILED', 'Transfer to expert failed but service completed', 'Critical', 'Critical', true, true, false, true, NOW()),
                    ('REFUND_FAILED', 'Automatic refund failed after payment', 'Critical', 'Critical', true, true, false, true, NOW()),
                    ('PAYMENT_PROCESSING_ERROR', 'Error processing payment in Stripe', 'Critical', 'Critical', true, true, false, true, NOW()),
                    ('STRIPE_WEBHOOK_ERROR', 'Error processing Stripe webhook', 'Critical', 'Critical', true, false, false, true, NOW()),

                    -- Error Log Types
                    ('SEARCH_CREATION_ERROR', 'Error creating search after payment', 'Error', 'High', true, false, false, true, NOW()),
                    ('EXPERT_ACCOUNT_VERIFICATION_FAILED', 'Expert account verification failed', 'Error', 'High', false, false, false, true, NOW()),
                    ('DATABASE_CONNECTION_ERROR', 'Database connection error', 'Error', 'High', true, false, false, true, NOW()),
                    ('EXTERNAL_API_ERROR', 'Error calling external API', 'Error', 'Medium', false, false, false, true, NOW()),

                    -- Warning Log Types
                    ('EXPERT_ACCOUNT_PENDING', 'Expert account pending verification', 'Warning', 'Medium', false, false, false, true, NOW()),
                    ('PAYMENT_RETRY_ATTEMPT', 'Payment retry attempt', 'Warning', 'Medium', false, false, false, true, NOW()),
                    ('USER_ACTION_LIMIT_EXCEEDED', 'User exceeded action limits', 'Warning', 'Low', false, false, false, true, NOW()),

                    -- Info Log Types
                    ('SERVICE_COMPLETED', 'Service completed successfully', 'Info', 'Low', false, false, false, true, NOW()),
                    ('REFUND_PROCESSED', 'Refund processed successfully', 'Info', 'Low', false, false, false, true, NOW()),
                    ('PAYMENT_SUCCESSFUL', 'Payment processed successfully', 'Info', 'Low', false, false, false, true, NOW()),
                    ('USER_LOGIN', 'User logged in', 'Info', 'Low', false, false, false, true, NOW()),
                    ('SEARCH_CREATED', 'Search created successfully', 'Info', 'Low', false, false, false, true, NOW()),
                    ('EXPERT_ACCOUNT_VERIFIED', 'Expert account verified', 'Info', 'Low', false, false, false, true, NOW())
                    ON CONFLICT ("Name") DO NOTHING;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019224616_AddLogTypeTableOnly') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251019224616_AddLogTypeTableOnly', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "Logs" DROP CONSTRAINT "FK_Logs_LogTypes_LogTypeId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    CREATE TABLE "Severities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(20) NOT NULL,
        "Description" character varying(100),
        "SortOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Severities" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    CREATE UNIQUE INDEX "IX_Severities_Name" ON "Severities" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN

                    INSERT INTO "Severities" ("Name", "Description", "SortOrder", "IsActive", "CreatedAt")
                    VALUES
                    ('Critical', 'Critical severity level', 1, true, NOW()),
                    ('High', 'High severity level', 2, true, NOW()),
                    ('Medium', 'Medium severity level', 3, true, NOW()),
                    ('Low', 'Low severity level', 4, true, NOW())
                    ON CONFLICT ("Name") DO NOTHING;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "LogTypes" ADD "SeverityId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN

                    UPDATE "LogTypes" 
                    SET "SeverityId" = (
                        CASE 
                            WHEN "Severity" = 'Critical' THEN (SELECT "Id" FROM "Severities" WHERE "Name" = 'Critical')
                            WHEN "Severity" = 'High' THEN (SELECT "Id" FROM "Severities" WHERE "Name" = 'High')
                            WHEN "Severity" = 'Medium' THEN (SELECT "Id" FROM "Severities" WHERE "Name" = 'Medium')
                            WHEN "Severity" = 'Low' THEN (SELECT "Id" FROM "Severities" WHERE "Name" = 'Low')
                            ELSE (SELECT "Id" FROM "Severities" WHERE "Name" = 'Low')
                        END
                    )
                    WHERE "SeverityId" IS NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "LogTypes" ALTER COLUMN "SeverityId" SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "LogTypes" DROP COLUMN "Severity";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    CREATE INDEX "IX_LogTypes_SeverityId" ON "LogTypes" ("SeverityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "Logs" ADD CONSTRAINT "FK_Logs_LogTypes_LogTypeId" FOREIGN KEY ("LogTypeId") REFERENCES "LogTypes" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    ALTER TABLE "LogTypes" ADD CONSTRAINT "FK_LogTypes_Severities_SeverityId" FOREIGN KEY ("SeverityId") REFERENCES "Severities" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019230221_AddSeverityTableAndUpdateLogType') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251019230221_AddSeverityTableAndUpdateLogType', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" DROP CONSTRAINT "FK_LogTypes_Severities_SeverityId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" DROP COLUMN "Category";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" ALTER COLUMN "SeverityId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" ALTER COLUMN "Name" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" ALTER COLUMN "Description" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    ALTER TABLE "LogTypes" ADD CONSTRAINT "FK_LogTypes_Severities_SeverityId" FOREIGN KEY ("SeverityId") REFERENCES "Severities" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019231824_SimplifyLogTypes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251019231824_SimplifyLogTypes', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019234253_RemoveLogLevelColumn') THEN
    ALTER TABLE "Logs" DROP COLUMN "LogLevel";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019234253_RemoveLogLevelColumn') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251019234253_RemoveLogLevelColumn', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103652_AddSeparateCancellationCounters') THEN
    ALTER TABLE "Appointments" ADD "ClientCancellationCount" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103652_AddSeparateCancellationCounters') THEN
    ALTER TABLE "Appointments" ADD "ExpertCancellationCount" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103652_AddSeparateCancellationCounters') THEN
    ALTER TABLE "Appointments" ADD "LastClientCancellationAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103652_AddSeparateCancellationCounters') THEN
    ALTER TABLE "Appointments" ADD "LastExpertCancellationAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103652_AddSeparateCancellationCounters') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021103652_AddSeparateCancellationCounters', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021103829_RemoveGlobalCancellationCount') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021103829_RemoveGlobalCancellationCount', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251028122232_AddColorToSystemStatuses') THEN
    ALTER TABLE "Appointments" DROP COLUMN "CancellationCount";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251028122232_AddColorToSystemStatuses') THEN
    ALTER TABLE "SystemStatuses" ADD "Color" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251028122232_AddColorToSystemStatuses') THEN
    ALTER TABLE "Appointments" ALTER COLUMN "ExpertCancellationCount" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251028122232_AddColorToSystemStatuses') THEN
    ALTER TABLE "Appointments" ALTER COLUMN "ClientCancellationCount" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251028122232_AddColorToSystemStatuses') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251028122232_AddColorToSystemStatuses', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    ALTER TABLE "SearchHires" ADD "ExpertAvailabilityId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    CREATE TABLE "ExpertAvailabilities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ExpertId" integer NOT NULL,
        "DaysOfWeek" text NOT NULL,
        "StartTime" interval NOT NULL,
        "EndTime" interval NOT NULL,
        "EffectiveFrom" timestamp with time zone NOT NULL,
        "EffectiveTo" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ExpertAvailabilities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExpertAvailabilities_ExpertProfiles_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "ExpertProfiles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    CREATE INDEX "IX_SearchHires_ExpertAvailabilityId" ON "SearchHires" ("ExpertAvailabilityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    CREATE INDEX "IX_ExpertAvailabilities_ExpertId_IsActive_EffectiveTo" ON "ExpertAvailabilities" ("ExpertId", "IsActive", "EffectiveTo") WHERE "EffectiveTo" IS NULL AND "IsActive" = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    ALTER TABLE "SearchHires" ADD CONSTRAINT "FK_SearchHires_ExpertAvailabilities_ExpertAvailabilityId" FOREIGN KEY ("ExpertAvailabilityId") REFERENCES "ExpertAvailabilities" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251101025058_AddExpertAvailabilitySystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251101025058_AddExpertAvailabilitySystem', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104115022_RemoveUnusedAppointmentFields') THEN
    ALTER TABLE "Appointments" DROP COLUMN "CompletedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104115022_RemoveUnusedAppointmentFields') THEN
    ALTER TABLE "Appointments" DROP COLUMN "CompletedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104115022_RemoveUnusedAppointmentFields') THEN
    ALTER TABLE "Appointments" DROP COLUMN "DisputeReason";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104115022_RemoveUnusedAppointmentFields') THEN
    ALTER TABLE "Appointments" DROP COLUMN "IsLocked";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104115022_RemoveUnusedAppointmentFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251104115022_RemoveUnusedAppointmentFields', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104232306_AddStripeFutureRequirementsToExpertProfile') THEN
    ALTER TABLE "SearchHires" DROP CONSTRAINT "FK_SearchHires_ExpertAvailabilities_ExpertAvailabilityId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104232306_AddStripeFutureRequirementsToExpertProfile') THEN
    DROP INDEX "IX_ExpertAvailabilities_ExpertId_IsActive_EffectiveTo";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104232306_AddStripeFutureRequirementsToExpertProfile') THEN
    ALTER TABLE "ExpertProfiles" ADD "StripeFutureDueAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104232306_AddStripeFutureRequirementsToExpertProfile') THEN
    ALTER TABLE "ExpertProfiles" ADD "StripeFutureRequirements" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104232306_AddStripeFutureRequirementsToExpertProfile') THEN
    CREATE INDEX "IX_ExpertAvailabilities_ExpertId" ON "ExpertAvailabilities" ("ExpertId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104232306_AddStripeFutureRequirementsToExpertProfile') THEN
    ALTER TABLE "SearchHires" ADD CONSTRAINT "FK_SearchHires_ExpertAvailabilities_ExpertAvailabilityId" FOREIGN KEY ("ExpertAvailabilityId") REFERENCES "ExpertAvailabilities" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251104232306_AddStripeFutureRequirementsToExpertProfile') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251104232306_AddStripeFutureRequirementsToExpertProfile', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Conversations" DROP CONSTRAINT "FK_Conversations_Users_ClientId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Conversations" DROP CONSTRAINT "FK_Conversations_Users_ExpertId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "FinancialTransactions" DROP CONSTRAINT "FK_FinancialTransactions_Users_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Messages" DROP CONSTRAINT "FK_Messages_Users_SenderId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Reviews" DROP CONSTRAINT "FK_Reviews_Users_ReviewerId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "SearchHires" DROP CONSTRAINT "FK_SearchHires_Users_ClientId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Users" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Users" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "SearchHires" ALTER COLUMN "ClientId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Reviews" ALTER COLUMN "ReviewerId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Messages" ALTER COLUMN "SenderId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "FinancialTransactions" ALTER COLUMN "UserId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Conversations" ALTER COLUMN "ExpertId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Conversations" ALTER COLUMN "ClientId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Conversations" ADD CONSTRAINT "FK_Conversations_Users_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Conversations" ADD CONSTRAINT "FK_Conversations_Users_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "FinancialTransactions" ADD CONSTRAINT "FK_FinancialTransactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Messages" ADD CONSTRAINT "FK_Messages_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "Reviews" ADD CONSTRAINT "FK_Reviews_Users_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    ALTER TABLE "SearchHires" ADD CONSTRAINT "FK_SearchHires_Users_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251114224416_MakeUserFieldsNullableForAccountDeletionAnonymization', '10.0.0');
    END IF;
END $EF$;
COMMIT;
