using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace newApi.Migrations
{
    /// <inheritdoc />
    public partial class R28_MUD_BD_ClawbackQueues : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 🛡️ FIX (drift de migraciones): idempotente (CREATE TABLE IF NOT EXISTS). La tabla pudo
            // crearse fuera de migración (hotfix de arranque / MCP) en prod. Sin IF NOT EXISTS,
            // MigrateAsync abortaba el lote con 42P07 (duplicate_table) y dejaba el esquema incompleto.
            // El DDL reproduce EXACTAMENTE lo que generaba migrationBuilder.CreateTable() para el modelo
            // ClawbackQueue, así que un MigrateAsync posterior lo aplica como no-op y registra el historial.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ClawbackQueues"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""StripeAccountId"" character varying(50) NULL,
                    ""SearchHireId"" integer NULL,
                    ""AmountMajor"" numeric NOT NULL,
                    ""Currency"" character varying(3) NOT NULL,
                    ""Reason"" character varying(40) NOT NULL,
                    ""Notes"" character varying(2000) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ResolvedAt"" timestamp with time zone NULL,
                    ""Resolution"" character varying(40) NULL,
                    ""ResolutionNotes"" character varying(2000) NULL,
                    ""ResolvedByAdminEmail"" character varying(200) NULL,
                    CONSTRAINT ""PK_ClawbackQueues"" PRIMARY KEY (""Id"")
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ClawbackQueues");
        }
    }
}
