using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace newApi.Migrations
{
    /// <inheritdoc />
    public partial class R28_MUD_BB_Dac7SellerSnapshots : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 🛡️ FIX (drift de migraciones / account-deletion 25P02):
            //
            //  1) IDEMPOTENTE. Esta migración NUNCA llegó a aplicarse en prod porque su CreateTable
            //     original chocaba con objetos creados a mano fuera de migración (ExchangeRateSnapshots
            //     y columnas de Users ya existían) → 42P07/42701 → MigrateAsync abortaba el lote en cada
            //     arranque y dejaba el esquema incompleto (faltaban Dac7SellerSnapshots/ClawbackQueues),
            //     lo que reventaba el borrado de cuenta con 25P02. Reescrita con ADD COLUMN/CREATE TABLE/
            //     CREATE INDEX "IF NOT EXISTS" para que aplique limpiamente sea cual sea el estado previo.
            //
            //  2) Dac7SellerSnapshots.ExpertProfileId pasa a NULLABLE + FK ON DELETE SET NULL (antes
            //     NOT NULL + RESTRICT). Decisión: al borrar (GDPR Art.17) a un experto, el snapshot DEBE
            //     preservarse por obligación legal DAC7/AEAT, pero DESVINCULADO (ExpertProfileId=NULL),
            //     en vez de bloquear el borrado. Ver Dac7SellerSnapshot.cs / AppDbContext.

            // ----- Columnas nuevas (idempotentes) -----
            migrationBuilder.Sql(@"
                ALTER TABLE ""Users""
                    ADD COLUMN IF NOT EXISTS ""FiscalCountry"" character varying(2) NULL,
                    ADD COLUMN IF NOT EXISTS ""FiscalCountryChangedAt"" timestamp with time zone NULL,
                    ADD COLUMN IF NOT EXISTS ""PreferredCurrency"" character varying(3) NULL,
                    ADD COLUMN IF NOT EXISTS ""PrivacyAcceptedAt"" timestamp with time zone NULL,
                    ADD COLUMN IF NOT EXISTS ""PrivacyVersion"" character varying(64) NULL,
                    ADD COLUMN IF NOT EXISTS ""TaxId"" character varying(50) NULL,
                    ADD COLUMN IF NOT EXISTS ""TaxIdCountry"" character varying(2) NULL,
                    ADD COLUMN IF NOT EXISTS ""TermsAcceptedAt"" timestamp with time zone NULL,
                    ADD COLUMN IF NOT EXISTS ""TermsVersion"" character varying(64) NULL;

                ALTER TABLE ""SearchServices""
                    ADD COLUMN IF NOT EXISTS ""Currency"" character varying(3) NOT NULL DEFAULT 'EUR';

                ALTER TABLE ""SearchHires""
                    ADD COLUMN IF NOT EXISTS ""Currency"" character varying(3) NOT NULL DEFAULT 'EUR';

                ALTER TABLE ""Reviews""
                    ADD COLUMN IF NOT EXISTS ""ReceivedInCountry"" character varying(2) NULL;

                ALTER TABLE ""FinancialTransactions""
                    ADD COLUMN IF NOT EXISTS ""Currency"" character varying(3) NOT NULL DEFAULT 'EUR';

                ALTER TABLE ""ExpertProfiles""
                    ADD COLUMN IF NOT EXISTS ""LastPayoutDate"" timestamp with time zone NULL,
                    ADD COLUMN IF NOT EXISTS ""RelocatedAt"" timestamp with time zone NULL,
                    ADD COLUMN IF NOT EXISTS ""RelocatedFromCountry"" character varying(2) NULL;

                ALTER TABLE ""ExpertAvailabilities""
                    ADD COLUMN IF NOT EXISTS ""Timezone"" character varying(50) NULL;

                ALTER TABLE ""Appointments""
                    ADD COLUMN IF NOT EXISTS ""ProposerTimezone"" character varying(64) NULL;
            ");

            // ----- Dac7SellerSnapshots (ExpertProfileId NULLABLE + FK ON DELETE SET NULL) -----
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Dac7SellerSnapshots"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ExpertProfileId"" integer NULL,
                    ""Year"" integer NOT NULL,
                    ""LegalFirstName"" character varying(200) NULL,
                    ""LegalLastName"" character varying(200) NULL,
                    ""DateOfBirth"" date NULL,
                    ""TinCountry"" character varying(2) NULL,
                    ""TinValue"" character varying(50) NULL,
                    ""FiscalCountry"" character varying(2) NULL,
                    ""VatNumber"" character varying(50) NULL,
                    ""AddressLine"" character varying(300) NULL,
                    ""AddressCity"" character varying(100) NULL,
                    ""AddressPostalCode"" character varying(20) NULL,
                    ""IbanLast4"" character varying(8) NULL,
                    ""GrossSalesQ1"" numeric NOT NULL,
                    ""GrossSalesQ2"" numeric NOT NULL,
                    ""GrossSalesQ3"" numeric NOT NULL,
                    ""GrossSalesQ4"" numeric NOT NULL,
                    ""PlatformFeesQ1"" numeric NOT NULL,
                    ""PlatformFeesQ2"" numeric NOT NULL,
                    ""PlatformFeesQ3"" numeric NOT NULL,
                    ""PlatformFeesQ4"" numeric NOT NULL,
                    ""TransactionCountQ1"" integer NOT NULL,
                    ""TransactionCountQ2"" integer NOT NULL,
                    ""TransactionCountQ3"" integer NOT NULL,
                    ""TransactionCountQ4"" integer NOT NULL,
                    ""ReportingCurrency"" character varying(3) NOT NULL,
                    ""SnapshotCreatedAt"" timestamp with time zone NOT NULL,
                    ""ReportedToAeatAt"" timestamp with time zone NULL,
                    ""AeatSubmissionReference"" character varying(50) NULL,
                    CONSTRAINT ""PK_Dac7SellerSnapshots"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Dac7SellerSnapshots_ExpertProfiles_ExpertProfileId""
                        FOREIGN KEY (""ExpertProfileId"") REFERENCES ""ExpertProfiles"" (""Id"") ON DELETE SET NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Dac7SellerSnapshot_Expert_Year_uq""
                    ON ""Dac7SellerSnapshots"" (""ExpertProfileId"", ""Year"");
            ");

            // ----- ExchangeRateSnapshots (ya existe en prod creada fuera de migración; IF NOT EXISTS) -----
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ExchangeRateSnapshots"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""BaseCurrency"" char(3) NOT NULL,
                    ""RatesJson"" jsonb NOT NULL,
                    ""Source"" character varying(64) NOT NULL,
                    ""RateDate"" date NOT NULL,
                    ""FetchedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_ExchangeRateSnapshots"" PRIMARY KEY (""Id"")
                );

                CREATE INDEX IF NOT EXISTS ""IX_ExchangeRateSnapshots_Base_Fetched""
                    ON ""ExchangeRateSnapshots"" (""BaseCurrency"", ""FetchedAt"" DESC);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Dac7SellerSnapshots");

            migrationBuilder.DropTable(
                name: "ExchangeRateSnapshots");

            migrationBuilder.DropColumn(
                name: "FiscalCountry",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "FiscalCountryChangedAt",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "PreferredCurrency",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "PrivacyAcceptedAt",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "PrivacyVersion",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "TaxId",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "TaxIdCountry",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "TermsAcceptedAt",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "TermsVersion",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "Currency",
                table: "SearchServices");

            migrationBuilder.DropColumn(
                name: "Currency",
                table: "SearchHires");

            migrationBuilder.DropColumn(
                name: "ReceivedInCountry",
                table: "Reviews");

            migrationBuilder.DropColumn(
                name: "Currency",
                table: "FinancialTransactions");

            migrationBuilder.DropColumn(
                name: "LastPayoutDate",
                table: "ExpertProfiles");

            migrationBuilder.DropColumn(
                name: "RelocatedAt",
                table: "ExpertProfiles");

            migrationBuilder.DropColumn(
                name: "RelocatedFromCountry",
                table: "ExpertProfiles");

            migrationBuilder.DropColumn(
                name: "Timezone",
                table: "ExpertAvailabilities");

            migrationBuilder.DropColumn(
                name: "ProposerTimezone",
                table: "Appointments");
        }
    }
}
