apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJlcml6bzkiLCJwYXNzd29yZCI6IkNvY2hlMTA5LyIsImVtYWlsIjoiZGNhc3RpbGxhYUBnbWFpbC5jb20iLCJhdXRoIjoiWlhKcGVtODVPa052WTJobE1UQTVMdz09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
