// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using newApi.DataLayer.Models;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250520183057_relationships")]
    partial class relationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.AI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AIs");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Ad", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("AdScore")
                        .HasColumnType("integer");

                    b.Property<string[]>("BadThings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<string[]>("GoodThings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("Highlighted")
                        .HasColumnType("boolean");

                    b.Property<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("boolean");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ScrappedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SellerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Dispute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReporterId")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionComments")
                        .HasColumnType("text");

                    b.Property<int>("SearchHireId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReporterId");

                    b.HasIndex("SearchHireId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.ExpertProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeAccountId")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ExpertProfiles");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.FinancialTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FinancialTransactions");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformWebsiteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.PlatformCategoryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlParameter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlatformId");

                    b.ToTable("PlatformCategoryMappings");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpertId")
                        .HasColumnType("integer");

                    b.Property<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("SearchHireId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("SearchHireId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.ReviewImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Search", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRevised")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastExecution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextExecution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchHire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<bool?>("ClientApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletionDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpertId")
                        .HasColumnType("integer");

                    b.Property<string>("ExpertTransferId")
                        .HasColumnType("text");

                    b.Property<int>("SearchId")
                        .HasColumnType("integer");

                    b.Property<int>("SearchServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("SearchId")
                        .IsUnique();

                    b.HasIndex("SearchServiceId");

                    b.ToTable("SearchHires");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchParameter", b =>
                {
                    b.Property<int>("SearchParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SearchParameterId"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LocationRange")
                        .HasColumnType("integer");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaxPrice")
                        .HasColumnType("integer");

                    b.Property<int?>("MinPrice")
                        .HasColumnType("integer");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int>("SearchId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShippingAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("StrictMatchOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("UserSearch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SearchParameterId");

                    b.HasIndex("SearchId");

                    b.ToTable("SearchParameters");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchParameterPlatform", b =>
                {
                    b.Property<int>("SearchParameterId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.HasKey("SearchParameterId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("SearchParameterPlatforms");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SearchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.HasIndex("SearchId");

                    b.ToTable("SearchResults");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchResultFiltered", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilterNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("FilteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("SearchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.HasIndex("SearchId");

                    b.ToTable("SearchResultsFiltered");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchServiceImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SearchServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SearchServiceId");

                    b.ToTable("SearchServiceImages");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdvanceIAModels")
                        .HasColumnType("boolean");

                    b.Property<bool>("AdvancedAdImagesAnalysis")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HumanFilter")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSearches")
                        .HasColumnType("integer");

                    b.Property<int>("MinSearchInterval")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceYearly")
                        .HasColumnType("numeric");

                    b.Property<string>("StripePriceIdMonthly")
                        .HasColumnType("text");

                    b.Property<string>("StripePriceIdYearly")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AIId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEmailNotificationEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWhatsAppNotificationEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AIId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int?>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AIId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWhatsAppEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AIId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsYearly")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.newApi.DataLayer.Models.PostGresModels.SearchService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationInHours")
                        .HasColumnType("integer");

                    b.Property<int>("ExpertProfileId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExpertProfileId");

                    b.ToTable("SearchServices");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Ad", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Platform", "Platform")
                        .WithMany("Ads")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Category", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Category", "Parent")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Dispute", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "Reporter")
                        .WithMany("DisputesReported")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.SearchHire", "SearchHire")
                        .WithMany("Disputes")
                        .HasForeignKey("SearchHireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporter");

                    b.Navigation("SearchHire");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.ExpertProfile", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "User")
                        .WithOne("ExpertProfile")
                        .HasForeignKey("newApi.DataLayer.Models.PostGresModels.ExpertProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.FinancialTransaction", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "User")
                        .WithMany("FinancialTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Like", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Ad", "Ad")
                        .WithMany("Likes")
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");

                    b.Navigation("User");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Log", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Notification", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.PlatformCategoryMapping", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Category", "Category")
                        .WithMany("PlatformCategoryMappings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Review", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "Expert")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "Reviewer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.SearchHire", "SearchHire")
                        .WithMany()
                        .HasForeignKey("SearchHireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Reviewer");

                    b.Navigation("SearchHire");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.ReviewImage", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Review", "Review")
                        .WithMany("ImagesCollection")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Search", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.SubscriptionPlan", null)
                        .WithMany("Searches")
                        .HasForeignKey("SubscriptionPlanId");

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "User")
                        .WithMany("Searches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchHire", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "Client")
                        .WithMany("SearchHiresAsClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "Expert")
                        .WithMany("SearchHiresAsExpert")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Search", "Search")
                        .WithOne("SearchHire")
                        .HasForeignKey("newApi.DataLayer.Models.PostGresModels.SearchHire", "SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.newApi.DataLayer.Models.PostGresModels.SearchService", "SearchService")
                        .WithMany("SearchHires")
                        .HasForeignKey("SearchServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Expert");

                    b.Navigation("Search");

                    b.Navigation("SearchService");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchParameter", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Search", "Search")
                        .WithMany("SearchParameters")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Search");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchParameterPlatform", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Platform", "Platform")
                        .WithMany("SearchParameterPlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.SearchParameter", "SearchParameter")
                        .WithMany("SearchParameterPlatforms")
                        .HasForeignKey("SearchParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("SearchParameter");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchResult", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Ad", "Ad")
                        .WithMany()
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Search", "Search")
                        .WithMany("SearchResults")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");

                    b.Navigation("Search");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchResultFiltered", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Ad", "Ad")
                        .WithMany()
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Search", "Search")
                        .WithMany()
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");

                    b.Navigation("Search");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchServiceImage", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.newApi.DataLayer.Models.PostGresModels.SearchService", "SearchService")
                        .WithMany("Images")
                        .HasForeignKey("SearchServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchService");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SystemSetting", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.AI", "AI")
                        .WithMany()
                        .HasForeignKey("AIId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AI");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.User", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.UserSetting", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.AI", "AI")
                        .WithMany()
                        .HasForeignKey("AIId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("newApi.DataLayer.Models.PostGresModels.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AI");

                    b.Navigation("User");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.UserSubscription", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.newApi.DataLayer.Models.PostGresModels.SearchService", b =>
                {
                    b.HasOne("newApi.DataLayer.Models.PostGresModels.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("newApi.DataLayer.Models.PostGresModels.ExpertProfile", "ExpertProfile")
                        .WithMany("SearchServices")
                        .HasForeignKey("ExpertProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Ad", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Category", b =>
                {
                    b.Navigation("PlatformCategoryMappings");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.ExpertProfile", b =>
                {
                    b.Navigation("SearchServices");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Platform", b =>
                {
                    b.Navigation("Ads");

                    b.Navigation("SearchParameterPlatforms");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Review", b =>
                {
                    b.Navigation("ImagesCollection");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.Search", b =>
                {
                    b.Navigation("SearchHire")
                        .IsRequired();

                    b.Navigation("SearchParameters");

                    b.Navigation("SearchResults");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchHire", b =>
                {
                    b.Navigation("Disputes");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SearchParameter", b =>
                {
                    b.Navigation("SearchParameterPlatforms");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.SubscriptionPlan", b =>
                {
                    b.Navigation("Searches");

                    b.Navigation("UserSubscriptions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.User", b =>
                {
                    b.Navigation("DisputesReported");

                    b.Navigation("ExpertProfile")
                        .IsRequired();

                    b.Navigation("FinancialTransactions");

                    b.Navigation("Likes");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("SearchHiresAsClient");

                    b.Navigation("SearchHiresAsExpert");

                    b.Navigation("Searches");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("newApi.DataLayer.Models.PostGresModels.newApi.DataLayer.Models.PostGresModels.SearchService", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("SearchHires");
                });
#pragma warning restore 612, 618
        }
    }
}
