-- ─────────────────────────────────────────────────────────────────────────────
-- 🛡️ Round 16 — Apply EmailVerificationCodes + User auth fields MANUALLY
-- ─────────────────────────────────────────────────────────────────────────────
-- Si el auto-migrate de Round 17 no se ejecutó (binario viejo, error de startup
-- silencioso, etc.) este script aplica la migración 20260530001038 a mano.
--
-- Ejecutar UNA SOLA VEZ por base de datos:
--   psql -h localhost -p 5433 -U admin -d atrapo -f apply_round16_migration_manual.sql
--   (o pegar en DBeaver/pgAdmin contra la BD local)
--
-- Es idempotente: usa IF NOT EXISTS y comprueba __EFMigrationsHistory antes de
-- insertar. Reiniciar la app después (NO es estrictamente necesario, pero limpia
-- el ChangeTracker de EF).
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

-- ── 1) Users: nuevos campos de auth password/OAuth Apple + bloqueo brute-force ──
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "AppleId" text NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailVerified" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailVerifiedAt" timestamp with time zone NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "PasswordChangedAt" timestamp with time zone NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "FailedLoginAttempts" integer NOT NULL DEFAULT 0;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "LockedUntil" timestamp with time zone NULL;

-- ── 2) Users: índices ────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE INDEX IF NOT EXISTS "IX_Users_GoogleId" ON "Users" ("GoogleId");
CREATE INDEX IF NOT EXISTS "IX_Users_AppleId" ON "Users" ("AppleId");

-- ── 3) EmailVerificationCodes: tabla nueva ───────────────────────────────────
CREATE TABLE IF NOT EXISTS "EmailVerificationCodes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NULL,
    "Email" character varying(320) NOT NULL,
    "Purpose" integer NOT NULL,
    "CodeHash" bytea NOT NULL,
    "Salt" bytea NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "AttemptCount" integer NOT NULL DEFAULT 0,
    "MaxAttempts" integer NOT NULL DEFAULT 5,
    "ConsumedAt" timestamp with time zone NULL,
    "RequestIp" character varying(45) NULL,
    "VerifyIp" character varying(45) NULL,
    "VerificationToken" character varying(64) NOT NULL,
    CONSTRAINT "PK_EmailVerificationCodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailVerificationCodes_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_EmailVerificationCodes_Email_Purpose"
    ON "EmailVerificationCodes" ("Email", "Purpose");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_EmailVerificationCodes_VerificationToken"
    ON "EmailVerificationCodes" ("VerificationToken");

CREATE INDEX IF NOT EXISTS "IX_EmailVerificationCodes_ExpiresAt"
    ON "EmailVerificationCodes" ("ExpiresAt");

CREATE INDEX IF NOT EXISTS "IX_EmailVerificationCodes_Email_Purpose_CreatedAt"
    ON "EmailVerificationCodes" ("Email", "Purpose", "CreatedAt");

CREATE INDEX IF NOT EXISTS "IX_EmailVerificationCodes_UserId"
    ON "EmailVerificationCodes" ("UserId");

-- ── 4) Backfill: usuarios OAuth existentes ya tienen email "verificado" ──────
UPDATE "Users"
SET "EmailVerified" = TRUE,
    "EmailVerifiedAt" = COALESCE("CreatedAt", CURRENT_TIMESTAMP)
WHERE "GoogleId" IS NOT NULL
  AND "EmailVerified" = FALSE
  AND "IsDeleted" = FALSE;

-- ── 5) Registrar la migración en __EFMigrationsHistory ───────────────────────
-- Solo si no está ya registrada (idempotente).
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260530001038_AddEmailVerificationCodesAndUserAuthFields', '10.0.8'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260530001038_AddEmailVerificationCodesAndUserAuthFields'
);

COMMIT;

-- Verificación rápida (correr después del COMMIT):
-- SELECT column_name FROM information_schema.columns
--   WHERE table_name = 'Users' AND column_name IN ('AppleId', 'EmailVerified', 'FailedLoginAttempts', 'LockedUntil');
-- → Debe devolver 4 filas.
--
-- SELECT COUNT(*) FROM "EmailVerificationCodes";
-- → Debe devolver 0 (tabla creada vacía).
